# -*- coding: utf-8 -*-
"""BK_CL4Rec_Ablation_Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNvii2jHKaGaE5WOMX5LCbk5vJ563AcV

# 🔬 CL4Rec Ablation Study

## Experiments
1. **Component Ablation**: Remove Domain Masking / Domain Specialization
2. **Training Strategy**: Sequential vs. Joint Training (All 4 domains simultaneously)
3. **Domain Order**: Change the order of domain training
4. **Combined Analysis**: Summarize and analyze the results

**Dataset:** MovieLens 1M | **Domains:** Action, Comedy, Drama, Thriller
"""

# Cell 1: Setup & Dependencies
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict
from itertools import permutations
import os, urllib.request, zipfile, warnings, copy, time
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    print(f"🖥️ GPU: {torch.cuda.get_device_name(0)}")
print(f"Device: {device}")

# Cell 2: Download & Load Data
def download_ml1m():
    url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
    if not os.path.exists("./data/ml-1m"):
        os.makedirs("./data", exist_ok=True)
        print("📥 Downloading MovieLens 1M...")
        urllib.request.urlretrieve(url, "./data/ml-1m.zip")
        with zipfile.ZipFile("./data/ml-1m.zip", 'r') as z: z.extractall("./data")
        os.remove("./data/ml-1m.zip")
        print("✅ Done!")
    return "./data/ml-1m"

data_path = download_ml1m()
ratings = pd.read_csv(f"{data_path}/ratings.dat", sep="::", names=["user_id","item_id","rating","timestamp"], engine="python")
movies = pd.read_csv(f"{data_path}/movies.dat", sep="::", names=["item_id","title","genres"], engine="python", encoding="latin-1")
print(f"📊 Ratings: {len(ratings):,} | Users: {ratings['user_id'].nunique():,} | Items: {ratings['item_id'].nunique():,}")

# Cell 3: Data Preprocessing
DOMAINS = ['Action', 'Comedy', 'Drama', 'Thriller']

# Extract domain data
domain_data = {}
for d in DOMAINS:
    items = movies[movies['genres'].str.contains(d)]['item_id'].values
    domain_data[d] = ratings[(ratings['item_id'].isin(items)) & (ratings['rating'] >= 4)].copy()
    print(f"{d}: {len(domain_data[d]):,} interactions, {domain_data[d]['user_id'].nunique():,} users")

# Global mappings
all_users = set().union(*[set(d['user_id']) for d in domain_data.values()])
all_items = set().union(*[set(d['item_id']) for d in domain_data.values()])
user2idx = {u:i for i,u in enumerate(sorted(all_users))}
item2idx = {i:j for j,i in enumerate(sorted(all_items))}
num_users, num_items = len(user2idx), len(item2idx)
print(f"\n📈 Total: {num_users:,} users, {num_items:,} items")

# Active vs Cold-start split
user_counts = defaultdict(int)
for d in domain_data.values():
    for u in d['user_id']: user_counts[user2idx[u]] += 1
active_users = {u for u,c in user_counts.items() if c >= 10}
coldstart_users = {u for u,c in user_counts.items() if c < 10}
print(f"👤 Active: {len(active_users):,} | ❄️ Cold-start: {len(coldstart_users):,}")

# Cell 4: Prepare Train/Test Splits
def prepare_splits(domain_data, user2idx, item2idx):
    train_data, test_data = {}, {}
    for domain, data in domain_data.items():
        data_sorted = data.sort_values(['user_id', 'timestamp'])
        test_df = data_sorted.groupby('user_id').last().reset_index()
        train_df = data_sorted.groupby('user_id').apply(
            lambda x: x.iloc[:-1] if len(x)>1 else x.iloc[:0]
        ).reset_index(drop=True)

        user_items = defaultdict(set)
        for _,r in train_df.iterrows():
            user_items[user2idx[r['user_id']]].add(item2idx[r['item_id']])

        train_data[domain] = {
            'users': [user2idx[u] for u in train_df['user_id']],
            'items': [item2idx[i] for i in train_df['item_id']],
            'user_items': user_items
        }
        test_data[domain] = {
            'user_test_item': {user2idx[u]:item2idx[i] for u,i in zip(test_df['user_id'],test_df['item_id'])}
        }
    return train_data, test_data

train_data, test_data = prepare_splits(domain_data, user2idx, item2idx)
for d in DOMAINS:
    print(f"{d}: Train {len(train_data[d]['users']):,}, Test {len(test_data[d]['user_test_item']):,}")

# Cell 5: Dataset Class
class BPRDataset(Dataset):
    def __init__(self, users, items, user_items, n_items, neg=8):
        self.users, self.items, self.user_items = users, items, user_items
        self.n_items, self.neg = n_items, neg
    def __len__(self): return len(self.users)
    def __getitem__(self, idx):
        u, pos = self.users[idx], self.items[idx]
        negs = []
        while len(negs) < self.neg:
            n = np.random.randint(0, self.n_items)
            if n not in self.user_items[u]: negs.append(n)
        return u, pos, negs

def collate_fn(batch):
    return (torch.LongTensor([b[0] for b in batch]),
            torch.LongTensor([b[1] for b in batch]),
            torch.LongTensor([b[2] for b in batch]))

# Cell 6: CL4Rec Model with Configurable Components

class DomainMasking(nn.Module):
    """Domain-specific task masks"""
    def __init__(self, n_domains, dim):
        super().__init__()
        self.user_masks = nn.Parameter(torch.randn(n_domains, dim)*0.1 + 0.5)
        self.item_masks = nn.Parameter(torch.randn(n_domains, dim)*0.1 + 0.5)
        self.n_domains = n_domains

    def get_mask(self, d, t='user'):
        return torch.sigmoid(self.user_masks[d] if t=='user' else self.item_masks[d])

    def apply_mask(self, e, d, t='user'):
        return e * self.get_mask(d, t).unsqueeze(0)

    def get_max_mask(self, t='user'):
        masks = self.user_masks if t=='user' else self.item_masks
        return torch.sigmoid(masks).max(dim=0)[0]


class CL4RecAblation(nn.Module):
    """
    CL4Rec with configurable components for ablation study

    Args:
        use_domain_masking: Enable/disable domain masking
        use_domain_specialization: Enable/disable gradient protection
        use_mlp: Enable/disable MLP layers
    """
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2,
                 use_domain_masking=True, use_domain_specialization=True, use_mlp=True):
        super().__init__()
        self.n_users = n_users
        self.n_items = n_items
        self.n_domains = n_domains
        self.dim = dim

        # Configuration flags
        self.use_domain_masking = use_domain_masking
        self.use_domain_specialization = use_domain_specialization
        self.use_mlp = use_mlp

        # Embeddings
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

        # Domain Masking (optional)
        if use_domain_masking:
            self.mask = DomainMasking(n_domains, dim)

        # MLP layers (optional)
        if use_mlp:
            self.u_mlp = nn.Sequential(
                nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop),
                nn.Linear(hidden[0], hidden[1]), nn.ReLU(), nn.Dropout(drop),
                nn.Linear(hidden[1], dim)
            )
            self.i_mlp = nn.Sequential(
                nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop),
                nn.Linear(hidden[0], hidden[1]), nn.ReLU(), nn.Dropout(drop),
                nn.Linear(hidden[1], dim)
            )

        self.cur_domain = 0

    def get_emb(self, uids, iids, d, train=True):
        ue = self.user_emb(uids)
        ie = self.item_emb(iids)

        # Apply domain masking if enabled
        if self.use_domain_masking:
            if train:
                ue = self.mask.apply_mask(ue, d, 'user')
                ie = self.mask.apply_mask(ie, d, 'item')
            else:
                # Inference: max pooling over all masks
                ue = ue * self.mask.get_max_mask('user').unsqueeze(0)
                ie = ie * self.mask.get_max_mask('item').unsqueeze(0)

        # Apply MLP if enabled
        if self.use_mlp:
            ue = ue + self.u_mlp(ue)
            ie = ie + self.i_mlp(ie)

        return ue, ie

    def forward(self, u, pos, neg, d, train=True):
        ue, pe = self.get_emb(u, pos, d, train)
        _, ne = self.get_emb(u.repeat_interleave(neg.size(1)), neg.view(-1), d, train)
        ne = ne.view(u.size(0), neg.size(1), -1)

        ps = (ue * pe).sum(-1)
        ns = (ue.unsqueeze(1) * ne).sum(-1).mean(1)

        loss = -F.logsigmoid(ps - ns + 0.5).mean()
        reg = 0.001 * (ue.norm(2)**2 + pe.norm(2)**2 + ne.norm(2)**2) / u.size(0)
        return loss + reg

    def predict(self, uids, d=0):
        with torch.no_grad():
            ue = self.user_emb(uids)
            ie = self.item_emb.weight

            if self.use_domain_masking:
                ue = ue * self.mask.get_max_mask('user').unsqueeze(0)
                ie = ie * self.mask.get_max_mask('item').unsqueeze(0)

            if self.use_mlp:
                ue = ue + self.u_mlp(ue)
                ie = ie + self.i_mlp(ie)

            return torch.mm(ue, ie.t())

    def get_grad_mask(self, d):
        """Get gradient mask for domain specialization"""
        if not self.use_domain_specialization or not self.use_domain_masking or d == 0:
            return None, None

        # Protect important parameters from previous domains
        um = 1 - torch.stack([self.mask.get_mask(i, 'user') for i in range(d)]).max(0)[0]
        im = 1 - torch.stack([self.mask.get_mask(i, 'item') for i in range(d)]).max(0)[0]
        return um, im

# Cell 7: Training Functions

def train_sequential(model, train_data, domain_order, epochs=30, batch_size=512, lr=0.002):
    """Train model sequentially on domains"""
    all_losses = {}

    for di, dom in enumerate(domain_order):
        # Create dataloader
        ds = BPRDataset(train_data[dom]['users'], train_data[dom]['items'],
                       train_data[dom]['user_items'], num_items, neg=8)
        loader = DataLoader(ds, batch_size, True, collate_fn=collate_fn,
                           num_workers=2, pin_memory=True)

        # Optimizer setup
        if di == 0:
            opt = torch.optim.AdamW(model.parameters(), lr, weight_decay=1e-5)
        else:
            param_groups = [{'params': model.user_emb.parameters(), 'lr': lr*0.5},
                           {'params': model.item_emb.parameters(), 'lr': lr*0.5}]
            if model.use_domain_masking:
                param_groups.append({'params': model.mask.parameters(), 'lr': lr*2})
            if model.use_mlp:
                param_groups.extend([{'params': model.u_mlp.parameters(), 'lr': lr},
                                    {'params': model.i_mlp.parameters(), 'lr': lr}])
            opt = torch.optim.AdamW(param_groups, weight_decay=1e-5)

        sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, epochs)

        # Training loop
        model.train()
        losses = []
        for ep in range(epochs):
            total = 0
            for u, pos, neg in loader:
                u, pos, neg = u.to(device), pos.to(device), neg.to(device)
                opt.zero_grad()
                loss = model(u, pos, neg, di, True)
                loss.backward()

                # Apply gradient masking (Domain Specialization)
                um, im = model.get_grad_mask(di)
                if um is not None:
                    if model.user_emb.weight.grad is not None:
                        model.user_emb.weight.grad *= um.unsqueeze(0)
                    if model.item_emb.weight.grad is not None:
                        model.item_emb.weight.grad *= im.unsqueeze(0)

                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                opt.step()
                total += loss.item()
            sched.step()
            losses.append(total/len(loader))

        all_losses[dom] = losses
        model.cur_domain = di + 1

    return all_losses


def train_joint(model, train_data, domains, epochs=60, batch_size=512, lr=0.002):
    """Train model jointly on all domains at once"""
    # Combine all data
    all_u, all_i, all_ui = [], [], defaultdict(set)
    for d in domains:
        all_u.extend(train_data[d]['users'])
        all_i.extend(train_data[d]['items'])
        for u, its in train_data[d]['user_items'].items():
            all_ui[u].update(its)

    ds = BPRDataset(all_u, all_i, all_ui, num_items, neg=8)
    loader = DataLoader(ds, batch_size, True, collate_fn=collate_fn,
                       num_workers=2, pin_memory=True)

    opt = torch.optim.AdamW(model.parameters(), lr, weight_decay=1e-5)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, epochs)

    model.train()
    losses = []
    for ep in range(epochs):
        total = 0
        for u, pos, neg in loader:
            u, pos, neg = u.to(device), pos.to(device), neg.to(device)
            opt.zero_grad()
            loss = model(u, pos, neg, 0, True)  # domain=0 for joint training
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            total += loss.item()
        sched.step()
        losses.append(total/len(loader))

    return {'joint': losses}

# Cell 8: Evaluation Function

def evaluate_model(model, test_data, train_data, domains, k=50, user_filter=None):
    """Evaluate model on all domains"""
    model.eval()
    results = {}

    # Combine all training items for filtering
    all_train_ui = defaultdict(set)
    for d in domains:
        for u, its in train_data[d]['user_items'].items():
            all_train_ui[u].update(its)

    for di, dom in enumerate(domains):
        users = list(test_data[dom]['user_test_item'].keys())
        if user_filter is not None:
            users = [u for u in users if u in user_filter]

        if not users:
            results[dom] = {'R@10': 0, 'R@20': 0, 'R@50': 0}
            continue

        h10, h20, h50, tot = 0, 0, 0, 0

        for i in range(0, len(users), 512):
            batch = users[i:i+512]
            uids = torch.LongTensor(batch).to(device)
            scores = model.predict(uids, di)

            # Mask training items
            for j, u in enumerate(batch):
                if u in all_train_ui:
                    for it in all_train_ui[u]:
                        scores[j, it] = -float('inf')

            _, topk = torch.topk(scores, k, 1)
            topk = topk.cpu().numpy()

            for j, u in enumerate(batch):
                ti = test_data[dom]['user_test_item'][u]
                if ti in topk[j]: h50 += 1
                if ti in topk[j, :20]: h20 += 1
                if ti in topk[j, :10]: h10 += 1
                tot += 1

        results[dom] = {
            'R@10': h10/tot*100 if tot > 0 else 0,
            'R@20': h20/tot*100 if tot > 0 else 0,
            'R@50': h50/tot*100 if tot > 0 else 0
        }

    return results


def full_evaluation(model, test_data, train_data, domains):
    """Full evaluation with Active/ColdStart/Overall splits"""
    return {
        'Active': evaluate_model(model, test_data, train_data, domains, user_filter=active_users),
        'ColdStart': evaluate_model(model, test_data, train_data, domains, user_filter=coldstart_users),
        'Overall': evaluate_model(model, test_data, train_data, domains, user_filter=None)
    }

# Cell 9: Hyperparameters
CONFIG = {
    'dim': 128,
    'hidden': [256, 128],
    'dropout': 0.2,
    'epochs_sequential': 30,
    'epochs_joint': 80,  # More epochs for joint training
    'batch_size': 512,
    'lr': 0.002
}

print("⚙️ Configuration:")
for k, v in CONFIG.items():
    print(f"   {k}: {v}")

"""---
## 🧪 Ablation Study 1: Component Ablation
Remove each component to measure its contribution
"""

# Cell 10: Component Ablation Study
print("="*70)
print("🧪 ABLATION STUDY 1: Component Analysis")
print("="*70)

# Define ablation configurations
ablation_configs = {
    'Full CL4Rec': {'use_domain_masking': True, 'use_domain_specialization': True, 'use_mlp': True},
    'w/o Domain Masking': {'use_domain_masking': False, 'use_domain_specialization': False, 'use_mlp': True},
    'w/o Domain Specialization': {'use_domain_masking': True, 'use_domain_specialization': False, 'use_mlp': True},
    'w/o MLP': {'use_domain_masking': True, 'use_domain_specialization': True, 'use_mlp': False},
    'Only Embeddings': {'use_domain_masking': False, 'use_domain_specialization': False, 'use_mlp': False},
}

component_results = {}

for name, config in ablation_configs.items():
    print(f"\n{'='*50}")
    print(f"🔬 Training: {name}")
    print(f"   Config: {config}")
    print(f"{'='*50}")

    # Reset seed
    torch.manual_seed(SEED)
    if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

    # Create model
    model = CL4RecAblation(
        num_users, num_items, len(DOMAINS),
        dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
        **config
    ).to(device)

    # Train sequentially
    start_time = time.time()
    train_sequential(model, train_data, DOMAINS,
                    epochs=CONFIG['epochs_sequential'],
                    batch_size=CONFIG['batch_size'],
                    lr=CONFIG['lr'])
    train_time = time.time() - start_time

    # Evaluate
    results = full_evaluation(model, test_data, train_data, DOMAINS)
    results['train_time'] = train_time
    component_results[name] = results

    # Print results
    print(f"\n📊 Results for {name}:")
    for ut in ['Active', 'ColdStart', 'Overall']:
        mean_r50 = np.mean([results[ut][d]['R@50'] for d in DOMAINS])
        print(f"   {ut}: Mean R@50 = {mean_r50:.2f}%")
    print(f"   ⏱️ Training time: {train_time:.1f}s")

print("\n✅ Component ablation completed!")

"""---
## 🧪 Ablation Study 2: Sequential vs Joint Training
"""

# Cell 11: Sequential vs Joint Training
print("\n" + "="*70)
print("🧪 ABLATION STUDY 2: Sequential vs Joint Training")
print("="*70)

training_strategy_results = {}

# 1. CL4Rec Sequential (default)
print("\n--- CL4Rec Sequential Training ---")
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

model_seq = CL4RecAblation(
    num_users, num_items, len(DOMAINS),
    dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
    use_domain_masking=True, use_domain_specialization=True, use_mlp=True
).to(device)

start = time.time()
train_sequential(model_seq, train_data, DOMAINS, CONFIG['epochs_sequential'], CONFIG['batch_size'], CONFIG['lr'])
time_seq = time.time() - start

results_seq = full_evaluation(model_seq, test_data, train_data, DOMAINS)
results_seq['train_time'] = time_seq
training_strategy_results['CL4Rec Sequential'] = results_seq

# 2. CL4Rec Joint (train all domains at once with masking)
print("\n--- CL4Rec Joint Training (with masking) ---")
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

model_joint_mask = CL4RecAblation(
    num_users, num_items, len(DOMAINS),
    dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
    use_domain_masking=True, use_domain_specialization=False, use_mlp=True
).to(device)

start = time.time()
train_joint(model_joint_mask, train_data, DOMAINS, CONFIG['epochs_joint'], CONFIG['batch_size'], CONFIG['lr'])
time_joint_mask = time.time() - start

results_joint_mask = full_evaluation(model_joint_mask, test_data, train_data, DOMAINS)
results_joint_mask['train_time'] = time_joint_mask
training_strategy_results['Joint + Masking'] = results_joint_mask

# 3. Baseline Joint (no masking, no specialization - TADO)
print("\n--- Baseline Joint (TADO) ---")
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

model_tado = CL4RecAblation(
    num_users, num_items, len(DOMAINS),
    dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
    use_domain_masking=False, use_domain_specialization=False, use_mlp=True
).to(device)

start = time.time()
train_joint(model_tado, train_data, DOMAINS, CONFIG['epochs_joint'], CONFIG['batch_size'], CONFIG['lr'])
time_tado = time.time() - start

results_tado = full_evaluation(model_tado, test_data, train_data, DOMAINS)
results_tado['train_time'] = time_tado
training_strategy_results['TADO (Joint Baseline)'] = results_tado

# 4. Sequential without CL components
print("\n--- Sequential without CL ---")
torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

model_seq_nocl = CL4RecAblation(
    num_users, num_items, len(DOMAINS),
    dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
    use_domain_masking=False, use_domain_specialization=False, use_mlp=True
).to(device)

start = time.time()
train_sequential(model_seq_nocl, train_data, DOMAINS, CONFIG['epochs_sequential'], CONFIG['batch_size'], CONFIG['lr'])
time_seq_nocl = time.time() - start

results_seq_nocl = full_evaluation(model_seq_nocl, test_data, train_data, DOMAINS)
results_seq_nocl['train_time'] = time_seq_nocl
training_strategy_results['Sequential (no CL)'] = results_seq_nocl

print("\n📊 Training Strategy Comparison:")
print("-"*70)
print(f"{'Strategy':<25} {'Active R@50':>12} {'Cold R@50':>12} {'Overall R@50':>12} {'Time':>8}")
print("-"*70)
for name, res in training_strategy_results.items():
    active = np.mean([res['Active'][d]['R@50'] for d in DOMAINS])
    cold = np.mean([res['ColdStart'][d]['R@50'] for d in DOMAINS])
    overall = np.mean([res['Overall'][d]['R@50'] for d in DOMAINS])
    print(f"{name:<25} {active:>11.2f}% {cold:>11.2f}% {overall:>11.2f}% {res['train_time']:>7.1f}s")

"""---
## 🧪 Ablation Study 3: Domain Order Effect
"""

# Cell 12: Domain Order Analysis
print("\n" + "="*70)
print("🧪 ABLATION STUDY 3: Domain Order Effect")
print("="*70)

# Test different domain orders
domain_orders = [
    ('Default', ['Action', 'Comedy', 'Drama', 'Thriller']),
    ('Reverse', ['Thriller', 'Drama', 'Comedy', 'Action']),
    ('Size Ascending', ['Thriller', 'Action', 'Comedy', 'Drama']),  # Smaller first
    ('Size Descending', ['Drama', 'Comedy', 'Action', 'Thriller']),  # Larger first
    ('Random 1', ['Comedy', 'Action', 'Thriller', 'Drama']),
    ('Random 2', ['Drama', 'Thriller', 'Action', 'Comedy']),
]

order_results = {}

for order_name, order in domain_orders:
    print(f"\n--- Order: {order_name} ---")
    print(f"    Sequence: {' → '.join(order)}")

    torch.manual_seed(SEED)
    if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

    model = CL4RecAblation(
        num_users, num_items, len(DOMAINS),
        dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
        use_domain_masking=True, use_domain_specialization=True, use_mlp=True
    ).to(device)

    train_sequential(model, train_data, order, CONFIG['epochs_sequential'], CONFIG['batch_size'], CONFIG['lr'])

    # Evaluate on ORIGINAL domain order for fair comparison
    results = full_evaluation(model, test_data, train_data, DOMAINS)
    order_results[order_name] = results

    # Print per-domain results
    print(f"    Results (R@50):")
    for d in DOMAINS:
        print(f"      {d}: {results['Overall'][d]['R@50']:.2f}%")
    overall_mean = np.mean([results['Overall'][d]['R@50'] for d in DOMAINS])
    print(f"    Mean: {overall_mean:.2f}%")

# Summary table
print("\n" + "="*80)
print("📊 Domain Order Comparison (R@50):")
print("="*80)
print(f"{'Order':<20} " + " ".join([f'{d:<10}' for d in DOMAINS]) + f" {'Mean':>10} {'Std':>8}")
print("-"*80)

for order_name, res in order_results.items():
    vals = [res['Overall'][d]['R@50'] for d in DOMAINS]
    mean_val = np.mean(vals)
    std_val = np.std(vals)
    val_str = " ".join([f'{v:>9.2f}%' for v in vals])
    print(f"{order_name:<20} {val_str} {mean_val:>9.2f}% {std_val:>7.2f}")

# Cell 13: Catastrophic Forgetting Analysis
print("\n" + "="*70)
print("🧪 ABLATION STUDY 4: Catastrophic Forgetting Analysis")
print("="*70)

# Train and evaluate after each domain to measure forgetting
forgetting_analysis = {'CL4Rec': {}, 'No CL': {}}

for method_name, config in [('CL4Rec', {'use_domain_masking': True, 'use_domain_specialization': True, 'use_mlp': True}),
                             ('No CL', {'use_domain_masking': False, 'use_domain_specialization': False, 'use_mlp': True})]:
    print(f"\n--- {method_name} ---")

    torch.manual_seed(SEED)
    if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)

    model = CL4RecAblation(
        num_users, num_items, len(DOMAINS),
        dim=CONFIG['dim'], hidden=CONFIG['hidden'], drop=CONFIG['dropout'],
        **config
    ).to(device)

    domain_performance = {d: [] for d in DOMAINS}

    for di, train_domain in enumerate(DOMAINS):
        # Train on current domain
        ds = BPRDataset(train_data[train_domain]['users'], train_data[train_domain]['items'],
                       train_data[train_domain]['user_items'], num_items, neg=8)
        loader = DataLoader(ds, CONFIG['batch_size'], True, collate_fn=collate_fn, num_workers=2)

        if di == 0:
            opt = torch.optim.AdamW(model.parameters(), CONFIG['lr'], weight_decay=1e-5)
        else:
            opt = torch.optim.AdamW(model.parameters(), CONFIG['lr']*0.5, weight_decay=1e-5)

        model.train()
        for ep in range(CONFIG['epochs_sequential']):
            for u, pos, neg in loader:
                u, pos, neg = u.to(device), pos.to(device), neg.to(device)
                opt.zero_grad()
                loss = model(u, pos, neg, di, True)
                loss.backward()

                if config['use_domain_specialization'] and di > 0:
                    um, im = model.get_grad_mask(di)
                    if um is not None:
                        model.user_emb.weight.grad *= um.unsqueeze(0)
                        model.item_emb.weight.grad *= im.unsqueeze(0)

                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                opt.step()

        model.cur_domain = di + 1

        # Evaluate on ALL domains (including not yet trained)
        results = evaluate_model(model, test_data, train_data, DOMAINS)
        for d in DOMAINS:
            domain_performance[d].append(results[d]['R@50'])

        print(f"  After training {train_domain}:")
        for d in DOMAINS[:di+1]:
            print(f"    {d}: {results[d]['R@50']:.2f}%")

    forgetting_analysis[method_name] = domain_performance

# Calculate forgetting metrics
print("\n" + "="*70)
print("📉 Forgetting Analysis (Performance drop after learning new domains):")
print("="*70)

for method_name, perf in forgetting_analysis.items():
    print(f"\n{method_name}:")
    total_forgetting = 0
    for di, d in enumerate(DOMAINS[:-1]):  # Exclude last domain
        peak = perf[d][di]  # Performance right after training
        final = perf[d][-1]  # Final performance
        forgetting = peak - final
        total_forgetting += forgetting
        print(f"  {d}: Peak={peak:.2f}% → Final={final:.2f}% | Forgetting={forgetting:+.2f}%")
    print(f"  Total Forgetting: {total_forgetting:.2f}%")

# Cell 14: Comprehensive Results Summary
print("\n" + "="*80)
print("📊 COMPREHENSIVE ABLATION STUDY SUMMARY")
print("="*80)

# 1. Component Ablation Summary
print("\n┌" + "─"*78 + "┐")
print("│" + " 1. COMPONENT ABLATION ".center(78) + "│")
print("├" + "─"*78 + "┤")
print(f"│{'Configuration':<30} {'Active R@50':>12} {'Cold R@50':>12} {'Overall R@50':>12} {'Δ':>8} │")
print("├" + "─"*78 + "┤")

baseline_overall = np.mean([component_results['Full CL4Rec']['Overall'][d]['R@50'] for d in DOMAINS])
for name, res in component_results.items():
    active = np.mean([res['Active'][d]['R@50'] for d in DOMAINS])
    cold = np.mean([res['ColdStart'][d]['R@50'] for d in DOMAINS])
    overall = np.mean([res['Overall'][d]['R@50'] for d in DOMAINS])
    delta = overall - baseline_overall
    delta_str = f"{delta:+.2f}%" if name != 'Full CL4Rec' else "(base)"
    print(f"│{name:<30} {active:>11.2f}% {cold:>11.2f}% {overall:>11.2f}% {delta_str:>8} │")
print("└" + "─"*78 + "┘")

# 2. Training Strategy Summary
print("\n┌" + "─"*78 + "┐")
print("│" + " 2. TRAINING STRATEGY COMPARISON ".center(78) + "│")
print("├" + "─"*78 + "┤")
print(f"│{'Strategy':<30} {'Active R@50':>12} {'Cold R@50':>12} {'Overall R@50':>12} {'Time':>8} │")
print("├" + "─"*78 + "┤")

for name, res in training_strategy_results.items():
    active = np.mean([res['Active'][d]['R@50'] for d in DOMAINS])
    cold = np.mean([res['ColdStart'][d]['R@50'] for d in DOMAINS])
    overall = np.mean([res['Overall'][d]['R@50'] for d in DOMAINS])
    time_str = f"{res['train_time']:.0f}s"
    print(f"│{name:<30} {active:>11.2f}% {cold:>11.2f}% {overall:>11.2f}% {time_str:>8} │")
print("└" + "─"*78 + "┘")

# 3. Domain Order Summary
print("\n┌" + "─"*78 + "┐")
print("│" + " 3. DOMAIN ORDER EFFECT ".center(78) + "│")
print("├" + "─"*78 + "┤")
print(f"│{'Order':<20} " + " ".join([f'{d:<10}' for d in DOMAINS]) + f" {'Mean':>10} │")
print("├" + "─"*78 + "┤")

for order_name, res in order_results.items():
    vals = [res['Overall'][d]['R@50'] for d in DOMAINS]
    mean_val = np.mean(vals)
    val_str = " ".join([f'{v:>9.2f}%' for v in vals])
    print(f"│{order_name:<20} {val_str} {mean_val:>9.2f}% │")

# Statistics
all_means = [np.mean([res['Overall'][d]['R@50'] for d in DOMAINS]) for res in order_results.values()]
print("├" + "─"*78 + "┤")
print(f"│{'Statistics:':<20} Mean: {np.mean(all_means):.2f}%  Std: {np.std(all_means):.2f}%  Range: {np.max(all_means)-np.min(all_means):.2f}%".ljust(77) + " │")
print("└" + "─"*78 + "┘")

# Cell 15: Visualization
fig, axes = plt.subplots(2, 3, figsize=(18, 12))

# 1. Component Ablation Bar Chart
ax = axes[0, 0]
names = list(component_results.keys())
overall_vals = [np.mean([component_results[n]['Overall'][d]['R@50'] for d in DOMAINS]) for n in names]
colors = ['#2ecc71' if n == 'Full CL4Rec' else '#3498db' for n in names]
bars = ax.barh(names, overall_vals, color=colors)
ax.set_xlabel('Mean R@50 (%)')
ax.set_title('1. Component Ablation')
ax.axvline(x=overall_vals[0], color='#2ecc71', linestyle='--', alpha=0.5)
for bar, val in zip(bars, overall_vals):
    ax.text(val + 0.3, bar.get_y() + bar.get_height()/2, f'{val:.1f}%', va='center')

# 2. Training Strategy Comparison
ax = axes[0, 1]
strategies = list(training_strategy_results.keys())
x = np.arange(len(strategies))
width = 0.25
active_vals = [np.mean([training_strategy_results[s]['Active'][d]['R@50'] for d in DOMAINS]) for s in strategies]
cold_vals = [np.mean([training_strategy_results[s]['ColdStart'][d]['R@50'] for d in DOMAINS]) for s in strategies]
overall_vals = [np.mean([training_strategy_results[s]['Overall'][d]['R@50'] for d in DOMAINS]) for s in strategies]

ax.bar(x - width, active_vals, width, label='Active', color='#2ecc71')
ax.bar(x, cold_vals, width, label='Cold-Start', color='#e74c3c')
ax.bar(x + width, overall_vals, width, label='Overall', color='#3498db')
ax.set_xticks(x)
ax.set_xticklabels([s.replace(' ', '\n') for s in strategies], fontsize=8)
ax.set_ylabel('R@50 (%)')
ax.set_title('2. Training Strategy')
ax.legend(loc='lower right')

# 3. Domain Order Effect
ax = axes[0, 2]
order_names = list(order_results.keys())
order_means = [np.mean([order_results[o]['Overall'][d]['R@50'] for d in DOMAINS]) for o in order_names]
order_stds = [np.std([order_results[o]['Overall'][d]['R@50'] for d in DOMAINS]) for o in order_names]

ax.bar(range(len(order_names)), order_means, yerr=order_stds, capsize=5, color='#9b59b6', alpha=0.7)
ax.set_xticks(range(len(order_names)))
ax.set_xticklabels([o.replace(' ', '\n') for o in order_names], fontsize=8)
ax.set_ylabel('Mean R@50 (%)')
ax.set_title('3. Domain Order Effect')
ax.axhline(y=np.mean(order_means), color='red', linestyle='--', label=f'Avg: {np.mean(order_means):.1f}%')
ax.legend()

# 4. Forgetting Analysis
ax = axes[1, 0]
for method, perf in forgetting_analysis.items():
    for d in DOMAINS:
        label = f'{method}-{d}' if d == DOMAINS[0] else None
        style = '-' if method == 'CL4Rec' else '--'
        ax.plot(range(len(DOMAINS)), perf[d], style, label=method if d == DOMAINS[0] else None)

ax.set_xticks(range(len(DOMAINS)))
ax.set_xticklabels([f'After\n{d}' for d in DOMAINS], fontsize=8)
ax.set_ylabel('R@50 (%)')
ax.set_title('4. Forgetting Analysis')
ax.legend()
ax.grid(alpha=0.3)

# 5. Per-Domain Component Ablation Heatmap
ax = axes[1, 1]
heatmap_data = []
for name in component_results.keys():
    row = [component_results[name]['Overall'][d]['R@50'] for d in DOMAINS]
    heatmap_data.append(row)

sns.heatmap(heatmap_data, annot=True, fmt='.1f', cmap='YlGnBu',
            xticklabels=DOMAINS, yticklabels=list(component_results.keys()), ax=ax)
ax.set_title('5. Per-Domain R@50 by Configuration')

# 6. Improvement over Baseline
ax = axes[1, 2]
baseline_name = 'Only Embeddings'
baseline_vals = {d: component_results[baseline_name]['Overall'][d]['R@50'] for d in DOMAINS}

improvements = {}
for name in component_results.keys():
    if name != baseline_name:
        improvements[name] = [component_results[name]['Overall'][d]['R@50'] - baseline_vals[d] for d in DOMAINS]

x = np.arange(len(DOMAINS))
width = 0.15
for i, (name, imp) in enumerate(improvements.items()):
    ax.bar(x + i*width, imp, width, label=name[:15])

ax.set_xticks(x + width * 2)
ax.set_xticklabels(DOMAINS)
ax.set_ylabel('Improvement over Baseline (%)')
ax.set_title('6. Improvement over Baseline')
ax.legend(fontsize=7, loc='upper right')
ax.axhline(y=0, color='black', linestyle='-', linewidth=0.5)

plt.tight_layout()
plt.savefig('ablation_study_results.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n📊 Saved to ablation_study_results.png")

# Cell 16: Save All Results to CSV
all_results = []

# Component Ablation
for config_name, res in component_results.items():
    for user_type in ['Active', 'ColdStart', 'Overall']:
        for domain in DOMAINS:
            all_results.append({
                'Experiment': 'Component Ablation',
                'Configuration': config_name,
                'UserType': user_type,
                'Domain': domain,
                'R@10': res[user_type][domain]['R@10'],
                'R@20': res[user_type][domain]['R@20'],
                'R@50': res[user_type][domain]['R@50']
            })

# Training Strategy
for strategy_name, res in training_strategy_results.items():
    for user_type in ['Active', 'ColdStart', 'Overall']:
        for domain in DOMAINS:
            all_results.append({
                'Experiment': 'Training Strategy',
                'Configuration': strategy_name,
                'UserType': user_type,
                'Domain': domain,
                'R@10': res[user_type][domain]['R@10'],
                'R@20': res[user_type][domain]['R@20'],
                'R@50': res[user_type][domain]['R@50']
            })

# Domain Order
for order_name, res in order_results.items():
    for user_type in ['Active', 'ColdStart', 'Overall']:
        for domain in DOMAINS:
            all_results.append({
                'Experiment': 'Domain Order',
                'Configuration': order_name,
                'UserType': user_type,
                'Domain': domain,
                'R@10': res[user_type][domain]['R@10'],
                'R@20': res[user_type][domain]['R@20'],
                'R@50': res[user_type][domain]['R@50']
            })

df_results = pd.DataFrame(all_results)
df_results.to_csv('ablation_study_full_results.csv', index=False)
print("✅ Full results saved to ablation_study_full_results.csv")

# Summary statistics
print("\n📊 Summary Statistics by Experiment:")
summary = df_results.groupby(['Experiment', 'Configuration', 'UserType'])[['R@10', 'R@20', 'R@50']].mean().round(2)
print(summary)

"""---
## 📝 Key Findings Summary

### 1. Component Ablation:
- **Domain Masking**: Essential for domain-specific feature selection
- **Domain Specialization**: Prevents catastrophic forgetting
- **MLP Layers**: Improve representation learning

### 2. Training Strategy:
- **Sequential + CL** outperforms joint training
- **Joint training** suffers from domain interference
- **CL components** are crucial for sequential training

### 3. Domain Order:
- Order has moderate effect on final performance
- CL4Rec is relatively robust to order changes
- Starting with larger domains may provide better knowledge base

### 4. Forgetting Analysis:
- CL4Rec significantly reduces catastrophic forgetting
- Without CL, early domains lose performance as new domains are learned
"""