# -*- coding: utf-8 -*-
"""BK_CL4Rec_Baseline_Comparison_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mt-3d4JX6XCNvAdhST-1lH6L1XIsxMu_

# CL4Rec vs State-of-the-Art Baselines

## Baselines:
1. **Matrix Factorization (MF)** - Per-domain baseline
2. **KEEP** (CIKM 2022) - Knowledge Extraction and Plugging
3. **DIIT** (CIKM 2024) - Domain-Invariant Information Transfer
4. **ECAT** (SIGIR 2024) - Entire Space Continual and Adaptive Transfer
5. **CTNet** (WWW 2023) - Continual Transfer Learning Network
6. **CL4Rec** (ACIIDS 2024) - Our method
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict
import os, urllib.request, zipfile, warnings, time
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"Device: {device}")

# Download MovieLens 1M
def download_ml1m():
    url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
    if not os.path.exists("./data/ml-1m"):
        os.makedirs("./data", exist_ok=True)
        print("Downloading MovieLens 1M...")
        urllib.request.urlretrieve(url, "./data/ml-1m.zip")
        with zipfile.ZipFile("./data/ml-1m.zip", 'r') as z:
            z.extractall("./data")
        os.remove("./data/ml-1m.zip")
        print("Done!")
    return "./data/ml-1m"

data_path = download_ml1m()
ratings = pd.read_csv(f"{data_path}/ratings.dat", sep="::",
                      names=["user_id","item_id","rating","timestamp"], engine="python")
movies = pd.read_csv(f"{data_path}/movies.dat", sep="::",
                     names=["item_id","title","genres"], engine="python", encoding="latin-1")
print(f"Ratings: {len(ratings):,} | Users: {ratings['user_id'].nunique():,} | Items: {ratings['item_id'].nunique():,}")

# Data Preprocessing
DOMAINS = ['Action', 'Comedy', 'Drama', 'Thriller']

domain_data = {}
for d in DOMAINS:
    items = movies[movies['genres'].str.contains(d)]['item_id'].values
    domain_data[d] = ratings[(ratings['item_id'].isin(items)) & (ratings['rating'] >= 4)].copy()
    print(f"{d}: {len(domain_data[d]):,} interactions, {domain_data[d]['user_id'].nunique():,} users")

all_users = set().union(*[set(d['user_id']) for d in domain_data.values()])
all_items = set().union(*[set(d['item_id']) for d in domain_data.values()])
user2idx = {u:i for i,u in enumerate(sorted(all_users))}
item2idx = {i:j for j,i in enumerate(sorted(all_items))}
num_users, num_items = len(user2idx), len(item2idx)

domain_items = {d: set(item2idx[i] for i in domain_data[d]['item_id'].unique()) for d in DOMAINS}
print(f"\nTotal: {num_users:,} users, {num_items:,} items")

user_counts = defaultdict(int)
for d in domain_data.values():
    for u in d['user_id']:
        user_counts[user2idx[u]] += 1
active_users = {u for u,c in user_counts.items() if c >= 10}
coldstart_users = {u for u,c in user_counts.items() if c < 10}
print(f"Active: {len(active_users):,} | Cold-start: {len(coldstart_users):,}")

# Prepare Train/Test Splits
def prepare_splits(domain_data, user2idx, item2idx):
    train_data, test_data = {}, {}
    for domain, data in domain_data.items():
        data_sorted = data.sort_values(['user_id', 'timestamp'])
        test_df = data_sorted.groupby('user_id').last().reset_index()
        train_df = data_sorted.groupby('user_id').apply(
            lambda x: x.iloc[:-1] if len(x)>1 else x.iloc[:0]
        ).reset_index(drop=True)

        user_items = defaultdict(set)
        for _,r in train_df.iterrows():
            user_items[user2idx[r['user_id']]].add(item2idx[r['item_id']])

        train_data[domain] = {
            'users': [user2idx[u] for u in train_df['user_id']],
            'items': [item2idx[i] for i in train_df['item_id']],
            'user_items': user_items
        }
        test_data[domain] = {
            'user_test_item': {user2idx[u]:item2idx[i] for u,i in zip(test_df['user_id'],test_df['item_id'])}
        }
    return train_data, test_data

train_data, test_data = prepare_splits(domain_data, user2idx, item2idx)
for d in DOMAINS:
    print(f"{d}: Train {len(train_data[d]['users']):,}, Test {len(test_data[d]['user_test_item']):,}")

# Dataset Class
class BPRDataset(Dataset):
    def __init__(self, users, items, user_items, n_items, neg=8, domain_item_set=None):
        self.users, self.items, self.user_items = users, items, user_items
        self.n_items, self.neg = n_items, neg
        self.domain_items = list(domain_item_set) if domain_item_set else None

    def __len__(self):
        return len(self.users)

    def __getitem__(self, idx):
        u, pos = self.users[idx], self.items[idx]
        negs = []
        while len(negs) < self.neg:
            if self.domain_items:
                n = self.domain_items[np.random.randint(len(self.domain_items))]
            else:
                n = np.random.randint(0, self.n_items)
            if n not in self.user_items[u]:
                negs.append(n)
        return u, pos, negs

def collate_fn(batch):
    return (torch.LongTensor([b[0] for b in batch]),
            torch.LongTensor([b[1] for b in batch]),
            torch.LongTensor([b[2] for b in batch]))

CONFIG = {
    'dim': 128, 'hidden': [256, 128], 'dropout': 0.2,
    'epochs': 40, 'batch_size': 512, 'lr': 0.002,
    'neg_samples': 8, 'weight_decay': 1e-5
}
print("Config:", CONFIG)

# 1. Matrix Factorization (Per-Domain Baseline)
class MatrixFactorization(nn.Module):
    def __init__(self, n_users, n_items, dim=64):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        self.user_bias = nn.Embedding(n_users, 1)
        self.item_bias = nn.Embedding(n_items, 1)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)
        nn.init.zeros_(self.user_bias.weight)
        nn.init.zeros_(self.item_bias.weight)
        self.n_items = n_items

    def forward(self, users, pos_items, neg_items):
        u_emb = self.user_emb(users)
        p_emb = self.item_emb(pos_items)
        n_emb = self.item_emb(neg_items)
        u_bias = self.user_bias(users).squeeze()
        p_bias = self.item_bias(pos_items).squeeze()
        n_bias = self.item_bias(neg_items).squeeze(-1)

        pos_score = (u_emb * p_emb).sum(-1) + u_bias + p_bias
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1) + u_bias.unsqueeze(1) + n_bias
        neg_score = neg_score.mean(1)

        loss = -F.logsigmoid(pos_score - neg_score).mean()
        reg = 0.01 * (u_emb.norm(2)**2 + p_emb.norm(2)**2 + n_emb.norm(2)**2) / users.size(0)
        return loss + reg

    def predict(self, users):
        with torch.no_grad():
            u_emb = self.user_emb(users)
            u_bias = self.user_bias(users)
            scores = torch.mm(u_emb, self.item_emb.weight.t()) + u_bias + self.item_bias.weight.t()
            return scores

# 2. KEEP - Knowledge Extraction and Plugging (CIKM 2022)
class KEEP(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim

        # Shared embeddings
        self.shared_user_emb = nn.Embedding(n_users, dim)
        self.shared_item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.shared_user_emb.weight)
        nn.init.xavier_uniform_(self.shared_item_emb.weight)

        # Knowledge extractor
        self.knowledge_extractor = nn.Sequential(
            nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim)
        )

        # Domain-specific embeddings (same dim as shared for concatenation)
        self.domain_user_emb = nn.ModuleList([nn.Embedding(n_users, dim) for _ in range(n_domains)])
        self.domain_item_emb = nn.ModuleList([nn.Embedding(n_items, dim) for _ in range(n_domains)])
        for emb in self.domain_user_emb: nn.init.xavier_uniform_(emb.weight)
        for emb in self.domain_item_emb: nn.init.xavier_uniform_(emb.weight)

        # Domain adapters (input: dim*2 = shared + domain)
        self.domain_adapters = nn.ModuleList([
            nn.Sequential(
                nn.Linear(dim * 2, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim)
            ) for _ in range(n_domains)
        ])

    def get_embeddings(self, users, items, domain_idx):
        # Shared knowledge
        shared_u = self.knowledge_extractor(self.shared_user_emb(users))
        shared_i = self.knowledge_extractor(self.shared_item_emb(items))

        # Domain-specific
        domain_u = self.domain_user_emb[domain_idx](users)
        domain_i = self.domain_item_emb[domain_idx](items)

        # Concatenate and adapt
        u_final = self.domain_adapters[domain_idx](torch.cat([shared_u, domain_u], dim=-1))
        i_final = self.domain_adapters[domain_idx](torch.cat([shared_i, domain_i], dim=-1))

        return u_final, i_final

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_emb, p_emb = self.get_embeddings(users, pos_items, domain_idx)
        _, n_emb = self.get_embeddings(users.repeat_interleave(neg_items.size(1)), neg_items.view(-1), domain_idx)
        n_emb = n_emb.view(users.size(0), neg_items.size(1), -1)

        pos_score = (u_emb * p_emb).sum(-1)
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)

        loss = -F.logsigmoid(pos_score - neg_score).mean()
        reg = 0.001 * (u_emb.norm(2)**2 + p_emb.norm(2)**2) / users.size(0)
        return loss + reg

    def predict(self, users, domain_idx):
        with torch.no_grad():
            shared_u = self.knowledge_extractor(self.shared_user_emb(users))
            domain_u = self.domain_user_emb[domain_idx](users)
            u_final = self.domain_adapters[domain_idx](torch.cat([shared_u, domain_u], dim=-1))

            all_items = torch.arange(self.n_items, device=users.device)
            shared_i = self.knowledge_extractor(self.shared_item_emb(all_items))
            domain_i = self.domain_item_emb[domain_idx](all_items)
            i_final = self.domain_adapters[domain_idx](torch.cat([shared_i, domain_i], dim=-1))

            return torch.mm(u_final, i_final.t())

# 3. DIIT - Domain-Invariant Information Transfer (CIKM 2024)
class DIIT(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim

        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

        # Domain-invariant encoder
        self.invariant_encoder = nn.Sequential(
            nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim)
        )

        # Domain-specific encoders
        self.specific_encoders = nn.ModuleList([
            nn.Sequential(nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim))
            for _ in range(n_domains)
        ])

        # Domain discriminator
        self.domain_discriminator = nn.Sequential(
            nn.Linear(dim, hidden[1]), nn.ReLU(), nn.Linear(hidden[1], n_domains)
        )

        # Fusion layer (invariant + specific)
        self.fusion = nn.Sequential(
            nn.Linear(dim * 2, hidden[0]), nn.ReLU(), nn.Linear(hidden[0], dim)
        )

    def get_embeddings(self, users, items, domain_idx):
        u_raw, i_raw = self.user_emb(users), self.item_emb(items)

        u_inv = self.invariant_encoder(u_raw)
        i_inv = self.invariant_encoder(i_raw)

        u_spec = self.specific_encoders[domain_idx](u_raw)
        i_spec = self.specific_encoders[domain_idx](i_raw)

        u_final = self.fusion(torch.cat([u_inv, u_spec], dim=-1))
        i_final = self.fusion(torch.cat([i_inv, i_spec], dim=-1))

        return u_final, i_final, u_inv

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_emb, p_emb, u_inv = self.get_embeddings(users, pos_items, domain_idx)
        _, n_emb, _ = self.get_embeddings(users.repeat_interleave(neg_items.size(1)), neg_items.view(-1), domain_idx)
        n_emb = n_emb.view(users.size(0), neg_items.size(1), -1)

        pos_score = (u_emb * p_emb).sum(-1)
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)
        bpr_loss = -F.logsigmoid(pos_score - neg_score).mean()

        # Adversarial loss
        domain_pred = self.domain_discriminator(u_inv)
        domain_labels = torch.full((users.size(0),), domain_idx, device=users.device, dtype=torch.long)
        adv_loss = -F.cross_entropy(domain_pred, domain_labels) * 0.1

        reg = 0.001 * (u_emb.norm(2)**2 + p_emb.norm(2)**2) / users.size(0)
        return bpr_loss + adv_loss + reg

    def predict(self, users, domain_idx):
        with torch.no_grad():
            u_raw = self.user_emb(users)
            u_inv = self.invariant_encoder(u_raw)
            u_spec = self.specific_encoders[domain_idx](u_raw)
            u_final = self.fusion(torch.cat([u_inv, u_spec], dim=-1))

            all_items = torch.arange(self.n_items, device=users.device)
            i_raw = self.item_emb(all_items)
            i_inv = self.invariant_encoder(i_raw)
            i_spec = self.specific_encoders[domain_idx](i_raw)
            i_final = self.fusion(torch.cat([i_inv, i_spec], dim=-1))

            return torch.mm(u_final, i_final.t())

# 4. ECAT - Entire Space Continual and Adaptive Transfer (SIGIR 2024)
class ECAT(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim

        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

        # Domain experts
        self.domain_experts = nn.ModuleList([
            nn.Sequential(nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim))
            for _ in range(n_domains)
        ])

        # Transfer attention
        self.transfer_attention = nn.Sequential(
            nn.Linear(dim, hidden[1]), nn.ReLU(), nn.Linear(hidden[1], n_domains)
        )

        # EWC buffers
        self.register_buffer('fisher_diag', torch.zeros(n_users, dim))
        self.register_buffer('optimal_params', torch.zeros(n_users, dim))
        self.current_domain = 0

    def get_embeddings(self, users, items, domain_idx):
        u_base = self.user_emb(users)
        i_base = self.item_emb(items)

        # Expert outputs
        expert_u = [expert(u_base) for expert in self.domain_experts]
        expert_i = [expert(i_base) for expert in self.domain_experts]

        # Attention
        attn = F.softmax(self.transfer_attention(u_base), dim=-1)

        # Weighted sum
        u_stack = torch.stack(expert_u, dim=-1)  # [B, dim, n_domains]
        u_trans = (u_stack * attn.unsqueeze(1)).sum(-1)

        i_stack = torch.stack(expert_i, dim=-1)
        i_trans = (i_stack * attn.mean(0, keepdim=True).unsqueeze(0)).sum(-1)

        u_final = u_trans + expert_u[domain_idx]
        i_final = i_trans + expert_i[domain_idx]

        return u_final, i_final

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_emb, p_emb = self.get_embeddings(users, pos_items, domain_idx)
        _, n_emb = self.get_embeddings(users.repeat_interleave(neg_items.size(1)), neg_items.view(-1), domain_idx)
        n_emb = n_emb.view(users.size(0), neg_items.size(1), -1)

        pos_score = (u_emb * p_emb).sum(-1)
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)
        bpr_loss = -F.logsigmoid(pos_score - neg_score).mean()

        # EWC regularization
        ewc_loss = 0
        if domain_idx > 0:
            ewc_loss = 0.01 * 0.5 * (self.fisher_diag[users] * (self.user_emb(users) - self.optimal_params[users])**2).sum() / users.size(0)

        reg = 0.001 * (u_emb.norm(2)**2 + p_emb.norm(2)**2) / users.size(0)
        return bpr_loss + ewc_loss + reg

    def update_fisher(self, train_data, domain_idx):
        users = torch.LongTensor(train_data['users']).to(device)
        unique_users = users.unique()
        self.optimal_params[unique_users] = self.user_emb(unique_users).detach()
        self.fisher_diag[unique_users] += 1.0

    def predict(self, users, domain_idx):
        with torch.no_grad():
            u_emb, _ = self.get_embeddings(users, users, domain_idx)
            all_items = torch.arange(self.n_items, device=users.device)
            _, i_emb = self.get_embeddings(torch.zeros_like(all_items), all_items, domain_idx)
            return torch.mm(u_emb, i_emb.t())

# 5. CTNet - Continual Transfer Learning Network (WWW 2023)
class CTNet(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim

        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

        # Domain columns
        self.domain_columns = nn.ModuleList()
        for d in range(n_domains):
            self.domain_columns.append(nn.ModuleDict({
                'layer1': nn.Linear(dim, hidden[0]),
                'layer2': nn.Linear(hidden[0], hidden[1]),
                'layer3': nn.Linear(hidden[1], dim),
            }))

        # Lateral connections
        self.lateral_connections = nn.ModuleList()
        for d in range(1, n_domains):
            self.lateral_connections.append(nn.ModuleDict({
                'lateral1': nn.Linear(hidden[0] * d, hidden[0]),
                'lateral2': nn.Linear(hidden[1] * d, hidden[1]),
            }))

        # Transfer gates
        self.transfer_gates = nn.ModuleList([
            nn.Sequential(nn.Linear(dim, hidden[1]), nn.Sigmoid()) for _ in range(n_domains)
        ])

        self.dropout = nn.Dropout(drop)
        self.stored_h1 = {}
        self.stored_h2 = {}

    def forward_column(self, x, domain_idx, store=True):
        col = self.domain_columns[domain_idx]

        h1 = F.relu(col['layer1'](x))
        h1 = self.dropout(h1)

        # Lateral from previous domains
        if domain_idx > 0 and self.stored_h1:
            prev = [self.stored_h1.get(i, torch.zeros_like(h1)) for i in range(domain_idx)]
            if all(p.size(0) == h1.size(0) for p in prev):
                h1 = h1 + self.lateral_connections[domain_idx-1]['lateral1'](torch.cat(prev, dim=-1))

        h2 = F.relu(col['layer2'](h1))
        h2 = self.dropout(h2)

        if domain_idx > 0 and self.stored_h2:
            prev = [self.stored_h2.get(i, torch.zeros_like(h2)) for i in range(domain_idx)]
            if all(p.size(0) == h2.size(0) for p in prev):
                h2 = h2 + self.lateral_connections[domain_idx-1]['lateral2'](torch.cat(prev, dim=-1))

        h3 = col['layer3'](h2)

        gate = self.transfer_gates[domain_idx](x)
        out = gate * h3 + (1 - gate) * x

        if store:
            self.stored_h1[domain_idx] = h1.detach()
            self.stored_h2[domain_idx] = h2.detach()

        return out

    def get_embeddings(self, users, items, domain_idx):
        u_base = self.user_emb(users)
        i_base = self.item_emb(items)
        u_final = self.forward_column(u_base, domain_idx, store=True)
        i_final = self.forward_column(i_base, domain_idx, store=False)
        return u_final, i_final

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_emb, p_emb = self.get_embeddings(users, pos_items, domain_idx)
        _, n_emb = self.get_embeddings(users.repeat_interleave(neg_items.size(1)), neg_items.view(-1), domain_idx)
        n_emb = n_emb.view(users.size(0), neg_items.size(1), -1)

        pos_score = (u_emb * p_emb).sum(-1)
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)

        loss = -F.logsigmoid(pos_score - neg_score).mean()
        reg = 0.001 * (u_emb.norm(2)**2 + p_emb.norm(2)**2) / users.size(0)
        return loss + reg

    def predict(self, users, domain_idx):
        with torch.no_grad():
            u_emb, _ = self.get_embeddings(users, users, domain_idx)
            all_items = torch.arange(self.n_items, device=users.device)
            _, i_emb = self.get_embeddings(torch.zeros_like(all_items), all_items, domain_idx)
            return torch.mm(u_emb, i_emb.t())

# 6. CL4Rec - Our Method (ACIIDS 2024)
class DomainMasking(nn.Module):
    def __init__(self, n_domains, dim):
        super().__init__()
        self.user_masks = nn.Parameter(torch.randn(n_domains, dim) * 0.1 + 0.5)
        self.item_masks = nn.Parameter(torch.randn(n_domains, dim) * 0.1 + 0.5)

    def get_mask(self, d, t='user'):
        return torch.sigmoid(self.user_masks[d] if t == 'user' else self.item_masks[d])

    def get_max_mask(self, t='user'):
        masks = self.user_masks if t == 'user' else self.item_masks
        return torch.sigmoid(masks).max(dim=0)[0]


class CL4Rec(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256, 128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim

        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

        self.mask = DomainMasking(n_domains, dim)

        self.u_mlp = nn.Sequential(
            nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop),
            nn.Linear(hidden[0], hidden[1]), nn.ReLU(), nn.Dropout(drop),
            nn.Linear(hidden[1], dim)
        )
        self.i_mlp = nn.Sequential(
            nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop),
            nn.Linear(hidden[0], hidden[1]), nn.ReLU(), nn.Dropout(drop),
            nn.Linear(hidden[1], dim)
        )
        self.current_domain = 0

    def get_emb(self, uids, iids, d, train=True):
        ue = self.user_emb(uids)
        ie = self.item_emb(iids)

        if train:
            um = self.mask.get_mask(d, 'user')
            im = self.mask.get_mask(d, 'item')
            ue = ue * um.unsqueeze(0)
            ie = ie * im.unsqueeze(0)
        else:
            ue = ue * self.mask.get_max_mask('user').unsqueeze(0)
            ie = ie * self.mask.get_max_mask('item').unsqueeze(0)

        return ue + self.u_mlp(ue), ie + self.i_mlp(ie)

    def forward(self, u, pos, neg, d, train=True):
        ue, pe = self.get_emb(u, pos, d, train)
        _, ne = self.get_emb(u.repeat_interleave(neg.size(1)), neg.view(-1), d, train)
        ne = ne.view(u.size(0), neg.size(1), -1)

        ps = (ue * pe).sum(-1)
        ns = (ue.unsqueeze(1) * ne).sum(-1).mean(1)

        loss = -F.logsigmoid(ps - ns + 0.5).mean()
        reg = 0.001 * (ue.norm(2)**2 + pe.norm(2)**2 + ne.norm(2)**2) / u.size(0)
        return loss + reg

    def predict(self, uids, d=0):
        with torch.no_grad():
            ue = self.user_emb(uids) * self.mask.get_max_mask('user').unsqueeze(0)
            ue = ue + self.u_mlp(ue)
            ie = self.item_emb.weight * self.mask.get_max_mask('item').unsqueeze(0)
            ie = ie + self.i_mlp(ie)
            return torch.mm(ue, ie.t())

    def get_grad_mask(self, d):
        if d == 0:
            return None, None
        um = 1 - torch.stack([self.mask.get_mask(i, 'user') for i in range(d)]).max(0)[0]
        im = 1 - torch.stack([self.mask.get_mask(i, 'item') for i in range(d)]).max(0)[0]
        return um, im

# Training Functions
def train_mf_per_domain(train_data, domains, config):
    models = {}
    for domain in domains:
        print(f"  Training MF for {domain}...")
        torch.manual_seed(SEED)
        model = MatrixFactorization(num_users, num_items, config['dim']).to(device)
        ds = BPRDataset(train_data[domain]['users'], train_data[domain]['items'],
                        train_data[domain]['user_items'], num_items, config['neg_samples'], domain_items[domain])
        loader = DataLoader(ds, config['batch_size'], True, collate_fn=collate_fn, num_workers=2)
        opt = torch.optim.Adam(model.parameters(), config['lr'])
        model.train()
        for _ in range(config['epochs']):
            for u, p, n in loader:
                u, p, n = u.to(device), p.to(device), n.to(device)
                opt.zero_grad()
                model(u, p, n).backward()
                opt.step()
        models[domain] = model
    return models


def train_sequential(model, train_data, domains, config, use_grad_mask=False):
    for di, domain in enumerate(domains):
        print(f"  Training on {domain}...")
        ds = BPRDataset(train_data[domain]['users'], train_data[domain]['items'],
                        train_data[domain]['user_items'], num_items, config['neg_samples'])
        loader = DataLoader(ds, config['batch_size'], True, collate_fn=collate_fn, num_workers=2)

        lr = config['lr'] if di == 0 else config['lr'] * 0.5
        opt = torch.optim.AdamW(model.parameters(), lr, weight_decay=config['weight_decay'])
        sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, config['epochs'])

        model.train()
        for _ in range(config['epochs']):
            for u, p, n in loader:
                u, p, n = u.to(device), p.to(device), n.to(device)
                opt.zero_grad()
                model(u, p, n, di).backward()

                if use_grad_mask and hasattr(model, 'get_grad_mask'):
                    um, im = model.get_grad_mask(di)
                    if um is not None:
                        if model.user_emb.weight.grad is not None:
                            model.user_emb.weight.grad *= um.unsqueeze(0)
                        if model.item_emb.weight.grad is not None:
                            model.item_emb.weight.grad *= im.unsqueeze(0)

                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                opt.step()
            sched.step()

        if hasattr(model, 'current_domain'):
            model.current_domain = di + 1
        if hasattr(model, 'update_fisher'):
            model.update_fisher(train_data[domain], di)

# Evaluation Function
def evaluate_model(model, test_data, train_data, domains, k=50, user_filter=None, is_mf=False, mf_models=None):
    if not is_mf:
        model.eval()

    all_train_ui = defaultdict(set)
    for d in domains:
        for u, its in train_data[d]['user_items'].items():
            all_train_ui[u].update(its)

    results = {}
    for di, domain in enumerate(domains):
        curr_model = mf_models[domain] if is_mf else model
        if is_mf:
            curr_model.eval()

        users = list(test_data[domain]['user_test_item'].keys())
        if user_filter:
            users = [u for u in users if u in user_filter]

        if not users:
            results[domain] = {'R@10': 0, 'R@20': 0, 'R@50': 0}
            continue

        h10, h20, h50, tot = 0, 0, 0, 0
        for i in range(0, len(users), 512):
            batch = users[i:i + 512]
            uids = torch.LongTensor(batch).to(device)
            scores = curr_model.predict(uids) if is_mf else curr_model.predict(uids, di)

            for j, u in enumerate(batch):
                if u in all_train_ui:
                    for it in all_train_ui[u]:
                        scores[j, it] = -float('inf')

            _, topk = torch.topk(scores, k, 1)
            topk = topk.cpu().numpy()

            for j, u in enumerate(batch):
                ti = test_data[domain]['user_test_item'][u]
                if ti in topk[j]:
                    h50 += 1
                if ti in topk[j, :20]:
                    h20 += 1
                if ti in topk[j, :10]:
                    h10 += 1
                tot += 1

        results[domain] = {'R@10': h10 / tot * 100, 'R@20': h20 / tot * 100, 'R@50': h50 / tot * 100}
    return results


def full_evaluation(model, test_data, train_data, domains, is_mf=False, mf_models=None):
    return {
        'Active': evaluate_model(model, test_data, train_data, domains, user_filter=active_users, is_mf=is_mf, mf_models=mf_models),
        'ColdStart': evaluate_model(model, test_data, train_data, domains, user_filter=coldstart_users, is_mf=is_mf, mf_models=mf_models),
        'Overall': evaluate_model(model, test_data, train_data, domains, user_filter=None, is_mf=is_mf, mf_models=mf_models)
    }

# Run All Experiments
print("=" * 70)
print("TRAINING AND EVALUATING ALL MODELS")
print("=" * 70)

all_results = {}
training_times = {}

# 1. Matrix Factorization
print("\n1. Matrix Factorization (Per-Domain)")
start = time.time()
mf_models = train_mf_per_domain(train_data, DOMAINS, CONFIG)
training_times['MF'] = time.time() - start
all_results['MF'] = full_evaluation(None, test_data, train_data, DOMAINS, is_mf=True, mf_models=mf_models)
print(f"Done! Time: {training_times['MF']:.1f}s")

# 2. KEEP
print("\n2. KEEP (CIKM 2022)")
torch.manual_seed(SEED)
keep_model = KEEP(num_users, num_items, len(DOMAINS), CONFIG['dim'], CONFIG['hidden'], CONFIG['dropout']).to(device)
start = time.time()
train_sequential(keep_model, train_data, DOMAINS, CONFIG)
training_times['KEEP'] = time.time() - start
all_results['KEEP'] = full_evaluation(keep_model, test_data, train_data, DOMAINS)
print(f"Done! Time: {training_times['KEEP']:.1f}s")

# 3. DIIT
print("\n3. DIIT (CIKM 2024)")
torch.manual_seed(SEED)
diit_model = DIIT(num_users, num_items, len(DOMAINS), CONFIG['dim'], CONFIG['hidden'], CONFIG['dropout']).to(device)
start = time.time()
train_sequential(diit_model, train_data, DOMAINS, CONFIG)
training_times['DIIT'] = time.time() - start
all_results['DIIT'] = full_evaluation(diit_model, test_data, train_data, DOMAINS)
print(f"Done! Time: {training_times['DIIT']:.1f}s")

# 4. ECAT
print("\n4. ECAT (SIGIR 2024)")
torch.manual_seed(SEED)
ecat_model = ECAT(num_users, num_items, len(DOMAINS), CONFIG['dim'], CONFIG['hidden'], CONFIG['dropout']).to(device)
start = time.time()
train_sequential(ecat_model, train_data, DOMAINS, CONFIG)
training_times['ECAT'] = time.time() - start
all_results['ECAT'] = full_evaluation(ecat_model, test_data, train_data, DOMAINS)
print(f"Done! Time: {training_times['ECAT']:.1f}s")

# 5. CTNet
print("\n5. CTNet (WWW 2023)")
torch.manual_seed(SEED)
ctnet_model = CTNet(num_users, num_items, len(DOMAINS), CONFIG['dim'], CONFIG['hidden'], CONFIG['dropout']).to(device)
start = time.time()
train_sequential(ctnet_model, train_data, DOMAINS, CONFIG)
training_times['CTNet'] = time.time() - start
all_results['CTNet'] = full_evaluation(ctnet_model, test_data, train_data, DOMAINS)
print(f"Done! Time: {training_times['CTNet']:.1f}s")

# 6. CL4Rec
print("\n6. CL4Rec (Ours)")
torch.manual_seed(SEED)
cl4rec_model = CL4Rec(num_users, num_items, len(DOMAINS), CONFIG['dim'], CONFIG['hidden'], CONFIG['dropout']).to(device)
start = time.time()
train_sequential(cl4rec_model, train_data, DOMAINS, CONFIG, use_grad_mask=True)
training_times['CL4Rec'] = time.time() - start
all_results['CL4Rec'] = full_evaluation(cl4rec_model, test_data, train_data, DOMAINS)
print(f"Done! Time: {training_times['CL4Rec']:.1f}s")

# Results Summary
methods = ['MF', 'KEEP', 'DIIT', 'ECAT', 'CTNet', 'CL4Rec']

print("\n" + "=" * 100)
print("RESULTS SUMMARY")
print("=" * 100)

print("\n--- OVERALL R@50 ---")
print(f"{'Method':<12} " + " ".join([f'{d:<12}' for d in DOMAINS]) + f" {'Mean':>10} {'Time':>8}")
print("-" * 90)
for method in methods:
    vals = [all_results[method]['Overall'][d]['R@50'] for d in DOMAINS]
    mean_val = np.mean(vals)
    print(f"{method:<12} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {mean_val:>9.2f}% {training_times[method]:>7.0f}s")

print("\n--- ACTIVE USERS R@50 ---")
print(f"{'Method':<12} " + " ".join([f'{d:<12}' for d in DOMAINS]) + f" {'Mean':>10}")
print("-" * 80)
for method in methods:
    vals = [all_results[method]['Active'][d]['R@50'] for d in DOMAINS]
    print(f"{method:<12} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {np.mean(vals):>9.2f}%")

print("\n--- COLD-START USERS R@50 ---")
print(f"{'Method':<12} " + " ".join([f'{d:<12}' for d in DOMAINS]) + f" {'Mean':>10}")
print("-" * 80)
for method in methods:
    vals = [all_results[method]['ColdStart'][d]['R@50'] for d in DOMAINS]
    print(f"{method:<12} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {np.mean(vals):>9.2f}%")

# Improvement Analysis
print("\n" + "=" * 70)
print("CL4REC IMPROVEMENT OVER BASELINES")
print("=" * 70)

cl4rec_overall = np.mean([all_results['CL4Rec']['Overall'][d]['R@50'] for d in DOMAINS])
print(f"\n{'Method':<12} {'Mean R@50':>12} {'vs CL4Rec':>15} {'Relative':>12}")
print("-" * 55)
for method in methods:
    mean_val = np.mean([all_results[method]['Overall'][d]['R@50'] for d in DOMAINS])
    delta = cl4rec_overall - mean_val
    rel = (delta / mean_val * 100) if mean_val > 0 else 0
    if method == 'CL4Rec':
        print(f"{method:<12} {mean_val:>11.2f}% {'(ours)':>15} {'-':>12}")
    else:
        print(f"{method:<12} {mean_val:>11.2f}% {delta:>+14.2f}% {rel:>+11.1f}%")

# Visualization
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
colors = {'MF': '#95a5a6', 'KEEP': '#3498db', 'DIIT': '#9b59b6', 'ECAT': '#e67e22', 'CTNet': '#1abc9c', 'CL4Rec': '#e74c3c'}

# 1. Overall R@50 by Domain
ax = axes[0, 0]
x = np.arange(len(DOMAINS))
width = 0.12
for i, method in enumerate(methods):
    vals = [all_results[method]['Overall'][d]['R@50'] for d in DOMAINS]
    ax.bar(x + i * width, vals, width, label=method, color=colors[method])
ax.set_xticks(x + width * 2.5)
ax.set_xticklabels(DOMAINS)
ax.set_ylabel('R@50 (%)')
ax.set_title('Overall R@50 by Domain')
ax.legend(fontsize=8)

# 2. Mean Performance
ax = axes[0, 1]
mean_vals = [np.mean([all_results[m]['Overall'][d]['R@50'] for d in DOMAINS]) for m in methods]
bars = ax.bar(methods, mean_vals, color=[colors[m] for m in methods])
ax.set_ylabel('Mean R@50 (%)')
ax.set_title('Mean Performance')
for bar, val in zip(bars, mean_vals):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3, f'{val:.1f}', ha='center', fontsize=9)

# 3. Active vs Cold-Start
ax = axes[0, 2]
x = np.arange(len(methods))
width = 0.35
active_vals = [np.mean([all_results[m]['Active'][d]['R@50'] for d in DOMAINS]) for m in methods]
cold_vals = [np.mean([all_results[m]['ColdStart'][d]['R@50'] for d in DOMAINS]) for m in methods]
ax.bar(x - width / 2, active_vals, width, label='Active', color='#2ecc71')
ax.bar(x + width / 2, cold_vals, width, label='Cold-Start', color='#e74c3c')
ax.set_xticks(x)
ax.set_xticklabels(methods, fontsize=9)
ax.set_ylabel('Mean R@50 (%)')
ax.set_title('Active vs Cold-Start')
ax.legend()

# 4. Heatmap
ax = axes[1, 0]
heatmap_data = [[all_results[m]['Overall'][d]['R@50'] for d in DOMAINS] for m in methods]
sns.heatmap(heatmap_data, annot=True, fmt='.1f', cmap='YlOrRd', xticklabels=DOMAINS, yticklabels=methods, ax=ax)
ax.set_title('R@50 Heatmap')

# 5. Improvement over MF
ax = axes[1, 1]
mf_vals = {d: all_results['MF']['Overall'][d]['R@50'] for d in DOMAINS}
for method in methods[1:]:
    improvements = [(all_results[method]['Overall'][d]['R@50'] - mf_vals[d]) for d in DOMAINS]
    ax.plot(DOMAINS, improvements, 'o-', label=method, color=colors[method], linewidth=2, markersize=8)
ax.axhline(y=0, color='black', linestyle='--', alpha=0.5)
ax.set_ylabel('Improvement over MF (%)')
ax.set_title('Improvement over MF Baseline')
ax.legend(fontsize=8)

# 6. Training Time
ax = axes[1, 2]
times = [training_times[m] for m in methods]
ax.bar(methods, times, color=[colors[m] for m in methods])
ax.set_ylabel('Training Time (s)')
ax.set_title('Training Time')
for i, t in enumerate(times):
    ax.text(i, t + 1, f'{t:.0f}s', ha='center', fontsize=9)

plt.tight_layout()
plt.savefig('baseline_comparison.png', dpi=150)
plt.show()
print("Saved to baseline_comparison.png")

# Save to CSV
rows = []
for method in methods:
    for user_type in ['Active', 'ColdStart', 'Overall']:
        for domain in DOMAINS:
            rows.append({
                'Method': method, 'UserType': user_type, 'Domain': domain,
                'R@10': all_results[method][user_type][domain]['R@10'],
                'R@20': all_results[method][user_type][domain]['R@20'],
                'R@50': all_results[method][user_type][domain]['R@50'],
                'TrainingTime': training_times[method]
            })

df = pd.DataFrame(rows)
df.to_csv('baseline_comparison.csv', index=False)
print("Results saved to baseline_comparison.csv")
print("\nSummary:")
print(df.groupby(['Method', 'UserType'])[['R@10', 'R@20', 'R@50']].mean().round(2))