# -*- coding: utf-8 -*-
"""BK_CL4Rec_ML1M_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4AjT_UJUICJlVNCt5ujwBG4Zdpp7yOc

# 🎯 CL4Rec: Continual Learning for Multi-Domain Recommendation
**Paper:** ACIIDS 2024 | **Dataset:** MovieLens 1M | **4 Domains:** Action, Comedy, Drama, Thriller
"""

# Cell 1: Setup
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict
import os, urllib.request, zipfile, warnings
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.is_available(): torch.cuda.manual_seed(SEED)
print(f"Device: {device}")

# Cell 2: Download Data
def download_ml1m():
    url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
    if not os.path.exists("./data/ml-1m"):
        os.makedirs("./data", exist_ok=True)
        print("Downloading...")
        urllib.request.urlretrieve(url, "./data/ml-1m.zip")
        with zipfile.ZipFile("./data/ml-1m.zip", 'r') as z: z.extractall("./data")
        os.remove("./data/ml-1m.zip")
    return "./data/ml-1m"

data_path = download_ml1m()
ratings = pd.read_csv(f"{data_path}/ratings.dat", sep="::", names=["user_id","item_id","rating","timestamp"], engine="python")
movies = pd.read_csv(f"{data_path}/movies.dat", sep="::", names=["item_id","title","genres"], engine="python", encoding="latin-1")
print(f"Ratings: {len(ratings):,}, Users: {ratings['user_id'].nunique():,}, Items: {ratings['item_id'].nunique():,}")

# Cell 3: Extract Domains
DOMAINS = ['Action', 'Comedy', 'Drama', 'Thriller']

domain_data = {}
for d in DOMAINS:
    items = movies[movies['genres'].str.contains(d)]['item_id'].values
    domain_data[d] = ratings[(ratings['item_id'].isin(items)) & (ratings['rating'] >= 4)].copy()
    print(f"{d}: {len(domain_data[d]):,} interactions, {domain_data[d]['user_id'].nunique():,} users")

# Mappings
all_users = set().union(*[set(d['user_id']) for d in domain_data.values()])
all_items = set().union(*[set(d['item_id']) for d in domain_data.values()])
user2idx = {u:i for i,u in enumerate(sorted(all_users))}
item2idx = {i:j for j,i in enumerate(sorted(all_items))}
num_users, num_items = len(user2idx), len(item2idx)
print(f"\nTotal: {num_users:,} users, {num_items:,} items")

# Active vs Cold-start
user_counts = defaultdict(int)
for d in domain_data.values():
    for u in d['user_id']: user_counts[user2idx[u]] += 1
active_users = {u for u,c in user_counts.items() if c >= 10}
coldstart_users = {u for u,c in user_counts.items() if c < 10}
print(f"Active: {len(active_users):,}, Cold-start: {len(coldstart_users):,}")

# Cell 4: Prepare Train/Test
train_data, test_data = {}, {}
for domain, data in domain_data.items():
    data_sorted = data.sort_values(['user_id', 'timestamp'])
    test_df = data_sorted.groupby('user_id').last().reset_index()
    train_df = data_sorted.groupby('user_id').apply(lambda x: x.iloc[:-1] if len(x)>1 else x.iloc[:0]).reset_index(drop=True)

    user_items = defaultdict(set)
    for _,r in train_df.iterrows(): user_items[user2idx[r['user_id']]].add(item2idx[r['item_id']])

    train_data[domain] = {'users': [user2idx[u] for u in train_df['user_id']],
                          'items': [item2idx[i] for i in train_df['item_id']], 'user_items': user_items}
    test_data[domain] = {'user_test_item': {user2idx[u]:item2idx[i] for u,i in zip(test_df['user_id'],test_df['item_id'])}}
    print(f"{domain}: Train {len(train_data[domain]['users']):,}, Test {len(test_data[domain]['user_test_item']):,}")

# Cell 5: Dataset
class BPRDataset(Dataset):
    def __init__(self, users, items, user_items, n_items, neg=8):
        self.users, self.items, self.user_items = users, items, user_items
        self.n_items, self.neg = n_items, neg
    def __len__(self): return len(self.users)
    def __getitem__(self, idx):
        u, pos = self.users[idx], self.items[idx]
        negs = []
        while len(negs) < self.neg:
            n = np.random.randint(0, self.n_items)
            if n not in self.user_items[u]: negs.append(n)
        return u, pos, negs

def collate(batch):
    return torch.LongTensor([b[0] for b in batch]), torch.LongTensor([b[1] for b in batch]), torch.LongTensor([b[2] for b in batch])

# Cell 6: CL4Rec Model
class DomainMasking(nn.Module):
    def __init__(self, n_domains, dim):
        super().__init__()
        self.user_masks = nn.Parameter(torch.randn(n_domains, dim)*0.1 + 0.5)
        self.item_masks = nn.Parameter(torch.randn(n_domains, dim)*0.1 + 0.5)
    def get_mask(self, d, t='user'): return torch.sigmoid(self.user_masks[d] if t=='user' else self.item_masks[d])
    def apply_mask(self, e, d, t='user'): return e * self.get_mask(d, t).unsqueeze(0)

class CL4Rec(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)
        self.mask = DomainMasking(n_domains, dim)
        self.u_mlp = nn.Sequential(nn.Linear(dim,hidden[0]),nn.ReLU(),nn.Dropout(drop),
                                   nn.Linear(hidden[0],hidden[1]),nn.ReLU(),nn.Dropout(drop),nn.Linear(hidden[1],dim))
        self.i_mlp = nn.Sequential(nn.Linear(dim,hidden[0]),nn.ReLU(),nn.Dropout(drop),
                                   nn.Linear(hidden[0],hidden[1]),nn.ReLU(),nn.Dropout(drop),nn.Linear(hidden[1],dim))
        self.cur_domain = 0

    def get_emb(self, uids, iids, d, train=True):
        ue, ie = self.user_emb(uids), self.item_emb(iids)
        if train:
            ue = self.mask.apply_mask(ue, d, 'user')
            ie = self.mask.apply_mask(ie, d, 'item')
        else:
            um = torch.stack([self.mask.get_mask(i,'user') for i in range(self.n_domains)]).max(0)[0]
            im = torch.stack([self.mask.get_mask(i,'item') for i in range(self.n_domains)]).max(0)[0]
            ue, ie = ue * um.unsqueeze(0), ie * im.unsqueeze(0)
        return ue + self.u_mlp(ue), ie + self.i_mlp(ie)

    def forward(self, u, pos, neg, d, train=True):
        ue, pe = self.get_emb(u, pos, d, train)
        _, ne = self.get_emb(u.repeat_interleave(neg.size(1)), neg.view(-1), d, train)
        ne = ne.view(u.size(0), neg.size(1), -1)
        ps = (ue * pe).sum(-1)
        ns = (ue.unsqueeze(1) * ne).sum(-1).mean(1)
        loss = -F.logsigmoid(ps - ns + 0.5).mean()
        reg = 0.001 * (ue.norm(2)**2 + pe.norm(2)**2 + ne.norm(2)**2) / u.size(0)
        return loss + reg

    def predict(self, uids, d):
        with torch.no_grad():
            ue = self.user_emb(uids)
            um = torch.stack([self.mask.get_mask(i,'user') for i in range(self.n_domains)]).max(0)[0]
            ue = (ue * um.unsqueeze(0)) + self.u_mlp(ue * um.unsqueeze(0))
            ie = self.item_emb.weight
            im = torch.stack([self.mask.get_mask(i,'item') for i in range(self.n_domains)]).max(0)[0]
            ie = (ie * im.unsqueeze(0)) + self.i_mlp(ie * im.unsqueeze(0))
            return torch.mm(ue, ie.t())

    def grad_mask(self, d):
        if d == 0: return None, None
        um = 1 - torch.stack([self.mask.get_mask(i,'user') for i in range(d)]).max(0)[0]
        im = 1 - torch.stack([self.mask.get_mask(i,'item') for i in range(d)]).max(0)[0]
        return um, im

# Cell 7: Training & Evaluation Functions
def train_domain(model, loader, d, opt, sched, epochs=40):
    model.train()
    losses = []
    for ep in tqdm(range(epochs), desc=f"Domain {d}"):
        total = 0
        for u, pos, neg in loader:
            u, pos, neg = u.to(device), pos.to(device), neg.to(device)
            opt.zero_grad()
            loss = model(u, pos, neg, d, True)
            loss.backward()
            um, im = model.grad_mask(d)
            if um is not None:
                if model.user_emb.weight.grad is not None: model.user_emb.weight.grad *= um.unsqueeze(0)
                if model.item_emb.weight.grad is not None: model.item_emb.weight.grad *= im.unsqueeze(0)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            total += loss.item()
        sched.step()
        losses.append(total/len(loader))
    return losses

def evaluate(model, test_d, train_ui, d, k=50, filt=None):
    model.eval()
    users = list(test_d['user_test_item'].keys())
    if filt: users = [u for u in users if u in filt]
    if not users: return 0,0,0
    h10, h20, h50, tot = 0, 0, 0, 0
    for i in range(0, len(users), 512):
        batch = users[i:i+512]
        uids = torch.LongTensor(batch).to(device)
        scores = model.predict(uids, d)
        for j, u in enumerate(batch):
            if u in train_ui:
                for it in train_ui[u]: scores[j, it] = -float('inf')
        _, topk = torch.topk(scores, k, 1)
        topk = topk.cpu().numpy()
        for j, u in enumerate(batch):
            ti = test_d['user_test_item'][u]
            if ti in topk[j]: h50 += 1
            if ti in topk[j,:20]: h20 += 1
            if ti in topk[j,:10]: h10 += 1
            tot += 1
    return h10/tot*100, h20/tot*100, h50/tot*100

# Cell 8: Train CL4Rec
print("="*60 + "\n🚀 TRAINING CL4REC\n" + "="*60)

EPOCHS, BATCH, LR, NEG = 40, 512, 0.002, 8

cl4rec = CL4Rec(num_users, num_items, len(DOMAINS), 128, [256,128], 0.2).to(device)
all_losses = {}

for di, dom in enumerate(DOMAINS):
    print(f"\n--- Domain {di+1}: {dom} ---")
    ds = BPRDataset(train_data[dom]['users'], train_data[dom]['items'], train_data[dom]['user_items'], num_items, NEG)
    loader = DataLoader(ds, BATCH, True, collate_fn=collate, num_workers=2, pin_memory=True)

    if di == 0:
        opt = torch.optim.AdamW(cl4rec.parameters(), LR, weight_decay=1e-5)
    else:
        opt = torch.optim.AdamW([{'params': cl4rec.user_emb.parameters(), 'lr': LR*0.5},
                                 {'params': cl4rec.item_emb.parameters(), 'lr': LR*0.5},
                                 {'params': cl4rec.mask.parameters(), 'lr': LR*2},
                                 {'params': cl4rec.u_mlp.parameters()}, {'params': cl4rec.i_mlp.parameters()}], LR, weight_decay=1e-5)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, EPOCHS)
    all_losses[dom] = train_domain(cl4rec, loader, di, opt, sched, EPOCHS)
    cl4rec.cur_domain = di + 1

    print("Eval after training:")
    for ei, ed in enumerate(DOMAINS[:di+1]):
        r10, r20, r50 = evaluate(cl4rec, test_data[ed], train_data[ed]['user_items'], ei)
        print(f"  {ed}: R@10={r10:.2f}%, R@20={r20:.2f}%, R@50={r50:.2f}%")

# Cell 9: Train Baseline (TADO)
print("\n" + "="*60 + "\n🎯 TRAINING BASELINE (TADO)\n" + "="*60)

class Baseline(nn.Module):
    def __init__(self, nu, ni, dim, hid, drop):
        super().__init__()
        self.ue = nn.Embedding(nu, dim); self.ie = nn.Embedding(ni, dim)
        nn.init.xavier_uniform_(self.ue.weight); nn.init.xavier_uniform_(self.ie.weight)
        self.umlp = nn.Sequential(nn.Linear(dim,hid[0]),nn.ReLU(),nn.Dropout(drop),nn.Linear(hid[0],hid[1]),nn.ReLU(),nn.Dropout(drop),nn.Linear(hid[1],dim))
        self.imlp = nn.Sequential(nn.Linear(dim,hid[0]),nn.ReLU(),nn.Dropout(drop),nn.Linear(hid[0],hid[1]),nn.ReLU(),nn.Dropout(drop),nn.Linear(hid[1],dim))
        self.ni = ni
    def forward(self, u, pos, neg):
        ue = self.ue(u) + self.umlp(self.ue(u))
        pe = self.ie(pos) + self.imlp(self.ie(pos))
        ne = self.ie(neg); ne = ne + self.imlp(ne.view(-1, ne.size(-1))).view(ne.size())
        ps, ns = (ue*pe).sum(-1), (ue.unsqueeze(1)*ne).sum(-1).mean(1)
        return -F.logsigmoid(ps - ns + 0.5).mean() + 0.001*(ue.norm(2)**2+pe.norm(2)**2+ne.norm(2)**2)/u.size(0)
    def predict(self, u):
        with torch.no_grad():
            ue = self.ue(u) + self.umlp(self.ue(u))
            ie = self.ie.weight + self.imlp(self.ie.weight)
            return torch.mm(ue, ie.t())

# Combine all data
all_u, all_i, all_ui = [], [], defaultdict(set)
for d in DOMAINS:
    all_u.extend(train_data[d]['users']); all_i.extend(train_data[d]['items'])
    for u, its in train_data[d]['user_items'].items(): all_ui[u].update(its)

base_ds = BPRDataset(all_u, all_i, all_ui, num_items, NEG)
base_loader = DataLoader(base_ds, BATCH, True, collate_fn=collate, num_workers=2, pin_memory=True)

baseline = Baseline(num_users, num_items, 128, [256,128], 0.2).to(device)
opt = torch.optim.AdamW(baseline.parameters(), LR, weight_decay=1e-5)
sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, EPOCHS*2)

baseline.train()
for ep in tqdm(range(EPOCHS*2), desc="Baseline"):
    for u, pos, neg in base_loader:
        u, pos, neg = u.to(device), pos.to(device), neg.to(device)
        opt.zero_grad()
        loss = baseline(u, pos, neg)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(baseline.parameters(), 1.0)
        opt.step()
    sched.step()

# Cell 10: Final Evaluation
print("\n" + "="*70 + "\n📊 FINAL EVALUATION: Active vs Cold-Start\n" + "="*70)

def eval_base(model, test_d, train_ui, k=50, filt=None):
    model.eval()
    users = list(test_d['user_test_item'].keys())
    if filt: users = [u for u in users if u in filt]
    if not users: return 0,0,0
    h10, h20, h50, tot = 0, 0, 0, 0
    for i in range(0, len(users), 512):
        batch = users[i:i+512]
        uids = torch.LongTensor(batch).to(device)
        scores = model.predict(uids)
        for j, u in enumerate(batch):
            if u in train_ui:
                for it in train_ui[u]: scores[j, it] = -float('inf')
        _, topk = torch.topk(scores, k, 1)
        topk = topk.cpu().numpy()
        for j, u in enumerate(batch):
            ti = test_d['user_test_item'][u]
            if ti in topk[j]: h50 += 1
            if ti in topk[j,:20]: h20 += 1
            if ti in topk[j,:10]: h10 += 1
            tot += 1
    return h10/tot*100, h20/tot*100, h50/tot*100

results = {'CL4Rec': {'Active':{}, 'ColdStart':{}, 'Overall':{}}, 'TADO': {'Active':{}, 'ColdStart':{}, 'Overall':{}}}

for di, dom in enumerate(DOMAINS):
    print(f"\n--- {dom} ---")
    for grp, flt, nm in [(active_users,'Active','Active'), (coldstart_users,'ColdStart','Cold-Start'), (None,'Overall','Overall')]:
        r10, r20, r50 = evaluate(cl4rec, test_data[dom], train_data[dom]['user_items'], di, 50, grp)
        results['CL4Rec'][flt][dom] = {'R@10':r10, 'R@20':r20, 'R@50':r50}
        r10b, r20b, r50b = eval_base(baseline, test_data[dom], all_ui, 50, grp)
        results['TADO'][flt][dom] = {'R@10':r10b, 'R@20':r20b, 'R@50':r50b}
    print(f"  CL4Rec - Active: {results['CL4Rec']['Active'][dom]['R@50']:.2f}%, Cold: {results['CL4Rec']['ColdStart'][dom]['R@50']:.2f}%, Overall: {results['CL4Rec']['Overall'][dom]['R@50']:.2f}%")
    print(f"  TADO   - Active: {results['TADO']['Active'][dom]['R@50']:.2f}%, Cold: {results['TADO']['ColdStart'][dom]['R@50']:.2f}%, Overall: {results['TADO']['Overall'][dom]['R@50']:.2f}%")

# Cell 11: Summary Table
print("\n" + "="*90 + "\n📈 SUMMARY RESULTS\n" + "="*90)

for metric in ['R@50', 'R@20', 'R@10']:
    print(f"\n{metric}:")
    print("-"*90)
    print(f"{'Method':<10} {'Type':<12} " + " ".join([f'{d:<12}' for d in DOMAINS]) + f" {'Mean':<10}")
    print("-"*90)
    for m in ['CL4Rec', 'TADO']:
        for ut in ['Active', 'ColdStart', 'Overall']:
            vals = [results[m][ut][d][metric] for d in DOMAINS]
            print(f"{m:<10} {ut:<12} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {np.mean(vals):>9.2f}%")

# Cell 12: Improvement Analysis
print("\n" + "="*70 + "\n📈 CL4REC IMPROVEMENT OVER TADO\n" + "="*70)
for metric in ['R@10', 'R@20', 'R@50']:
    print(f"\n{metric}:")
    for ut in ['Active', 'ColdStart', 'Overall']:
        cl = np.mean([results['CL4Rec'][ut][d][metric] for d in DOMAINS])
        ta = np.mean([results['TADO'][ut][d][metric] for d in DOMAINS])
        imp = cl - ta
        rel = (imp/ta*100) if ta > 0 else 0
        print(f"  {ut:<12}: {imp:+.2f}% ({rel:+.1f}% rel) [CL4Rec: {cl:.2f}% vs TADO: {ta:.2f}%]")

# Cell 13: Visualization
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# R@50 by domain
ax = axes[0,0]
x = np.arange(len(DOMAINS)); w = 0.35
ax.bar(x-w/2, [results['CL4Rec']['Overall'][d]['R@50'] for d in DOMAINS], w, label='CL4Rec', color='#2ecc71')
ax.bar(x+w/2, [results['TADO']['Overall'][d]['R@50'] for d in DOMAINS], w, label='TADO', color='#3498db')
ax.set_xticks(x); ax.set_xticklabels(DOMAINS); ax.legend(); ax.set_ylabel('R@50 (%)'); ax.set_title('R@50 by Domain'); ax.grid(axis='y', alpha=0.3)

# Active vs Cold-Start
ax = axes[0,1]
cats = ['Active', 'ColdStart']; x2 = np.arange(2)
ax.bar(x2-w/2, [np.mean([results['CL4Rec'][c][d]['R@50'] for d in DOMAINS]) for c in cats], w, label='CL4Rec', color='#2ecc71')
ax.bar(x2+w/2, [np.mean([results['TADO'][c][d]['R@50'] for d in DOMAINS]) for c in cats], w, label='TADO', color='#3498db')
ax.set_xticks(x2); ax.set_xticklabels(cats); ax.legend(); ax.set_ylabel('Mean R@50 (%)'); ax.set_title('Active vs Cold-Start'); ax.grid(axis='y', alpha=0.3)

# Training loss
ax = axes[1,0]
for d in DOMAINS:
    if d in all_losses: ax.plot(all_losses[d], label=d)
ax.legend(); ax.set_xlabel('Epoch'); ax.set_ylabel('Loss'); ax.set_title('Training Loss'); ax.grid(alpha=0.3)

# Heatmap
ax = axes[1,1]
imp_mat = [[results['CL4Rec'][ut][d]['R@50'] - results['TADO'][ut][d]['R@50'] for ut in ['Active','ColdStart','Overall']] for d in DOMAINS]
sns.heatmap(imp_mat, annot=True, fmt='.1f', cmap='RdYlGn', center=0, xticklabels=['Active','ColdStart','Overall'], yticklabels=DOMAINS, ax=ax)
ax.set_title('CL4Rec Improvement (R@50 %)')

plt.tight_layout()
plt.savefig('cl4rec_results.png', dpi=150)
plt.show()
print("\n✅ Saved to cl4rec_results.png")

# Cell 14: Save Results
rows = []
for m in ['CL4Rec', 'TADO']:
    for ut in ['Active', 'ColdStart', 'Overall']:
        for d in DOMAINS:
            rows.append({'Method':m, 'UserType':ut, 'Domain':d, **results[m][ut][d]})
df = pd.DataFrame(rows)
df.to_csv('cl4rec_results.csv', index=False)
print("✅ Saved to cl4rec_results.csv")
print("\n" + "="*60 + "\n🎉 EXPERIMENT COMPLETE!\n" + "="*60)
print(df.groupby(['Method','UserType'])[['R@10','R@20','R@50']].mean().round(2))