# -*- coding: utf-8 -*-
"""CL4Rec_Baselines_Optimized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lF2nGipibKC9R_642pk8dePMbhMJhN49

# CL4Rec vs State-of-the-Art Baselines (Optimized)

## Baselines:
1. **Matrix Factorization (MF)** - Per-domain baseline
2. **KEEP** (CIKM 2022) - Knowledge Extraction and Plugging
3. **DIIT** (CIKM 2024) - Domain-Invariant Information Transfer
4. **ECAT** (SIGIR 2024) - Entire Space Continual and Adaptive Transfer
5. **CTNet** (WWW 2023) - Continual Transfer Learning Network
6. **CL4Rec** (ACIIDS 2024) - Our method ⭐
"""

# Cell 1: Setup
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict
import urllib.request, zipfile, warnings, time
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.backends.cudnn.deterministic = True
    print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"Device: {device}")

# Cell 2: Download Data
def download_ml1m():
    url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
    if not os.path.exists("./data/ml-1m"):
        os.makedirs("./data", exist_ok=True)
        print("Downloading MovieLens 1M...")
        urllib.request.urlretrieve(url, "./data/ml-1m.zip")
        with zipfile.ZipFile("./data/ml-1m.zip", 'r') as z:
            z.extractall("./data")
        os.remove("./data/ml-1m.zip")
        print("Done!")
    return "./data/ml-1m"

data_path = download_ml1m()
ratings = pd.read_csv(f"{data_path}/ratings.dat", sep="::",
                      names=["user_id","item_id","rating","timestamp"], engine="python")
movies = pd.read_csv(f"{data_path}/movies.dat", sep="::",
                     names=["item_id","title","genres"], engine="python", encoding="latin-1")
print(f"Ratings: {len(ratings):,} | Users: {ratings['user_id'].nunique():,} | Items: {ratings['item_id'].nunique():,}")

# Cell 3: Preprocessing
DOMAINS = ['Action', 'Comedy', 'Drama', 'Thriller']

domain_data = {}
for d in DOMAINS:
    items = movies[movies['genres'].str.contains(d)]['item_id'].values
    domain_data[d] = ratings[(ratings['item_id'].isin(items)) & (ratings['rating'] >= 4)].copy()
    print(f"{d}: {len(domain_data[d]):,} interactions")

all_users = set().union(*[set(d['user_id']) for d in domain_data.values()])
all_items = set().union(*[set(d['item_id']) for d in domain_data.values()])
user2idx = {u:i for i,u in enumerate(sorted(all_users))}
item2idx = {i:j for j,i in enumerate(sorted(all_items))}
num_users, num_items = len(user2idx), len(item2idx)

domain_items = {d: set(item2idx[i] for i in domain_data[d]['item_id'].unique()) for d in DOMAINS}
print(f"\nTotal: {num_users:,} users, {num_items:,} items")

user_counts = defaultdict(int)
for d in domain_data.values():
    for u in d['user_id']: user_counts[user2idx[u]] += 1
active_users = {u for u,c in user_counts.items() if c >= 10}
coldstart_users = {u for u,c in user_counts.items() if c < 10}
print(f"Active: {len(active_users):,} | Cold-start: {len(coldstart_users):,}")

# Cell 4: Train/Test Split
def prepare_splits(domain_data, user2idx, item2idx):
    train_data, test_data = {}, {}
    for domain, data in domain_data.items():
        data_sorted = data.sort_values(['user_id', 'timestamp'])
        test_df = data_sorted.groupby('user_id').last().reset_index()
        train_df = data_sorted.groupby('user_id').apply(
            lambda x: x.iloc[:-1] if len(x)>1 else x.iloc[:0]
        ).reset_index(drop=True)
        user_items = defaultdict(set)
        for _,r in train_df.iterrows():
            user_items[user2idx[r['user_id']]].add(item2idx[r['item_id']])
        train_data[domain] = {'users': [user2idx[u] for u in train_df['user_id']],
                              'items': [item2idx[i] for i in train_df['item_id']],
                              'user_items': user_items}
        test_data[domain] = {'user_test_item': {user2idx[u]:item2idx[i]
                             for u,i in zip(test_df['user_id'],test_df['item_id'])}}
    return train_data, test_data

train_data, test_data = prepare_splits(domain_data, user2idx, item2idx)
for d in DOMAINS:
    print(f"{d}: Train {len(train_data[d]['users']):,}, Test {len(test_data[d]['user_test_item']):,}")

# Cell 5: Dataset & Config
class BPRDataset(Dataset):
    def __init__(self, users, items, user_items, n_items, neg=8, domain_item_set=None):
        self.users, self.items, self.user_items = users, items, user_items
        self.n_items, self.neg = n_items, neg
        self.domain_items = list(domain_item_set) if domain_item_set else None
    def __len__(self): return len(self.users)
    def __getitem__(self, idx):
        u, pos = self.users[idx], self.items[idx]
        negs = []
        while len(negs) < self.neg:
            n = self.domain_items[np.random.randint(len(self.domain_items))] if self.domain_items else np.random.randint(0, self.n_items)
            if n not in self.user_items[u]: negs.append(n)
        return u, pos, negs

def collate_fn(batch):
    return (torch.LongTensor([b[0] for b in batch]),
            torch.LongTensor([b[1] for b in batch]),
            torch.LongTensor([b[2] for b in batch]))

# Config cho các baseline (standard)
CONFIG_BASELINE = {'dim': 128, 'hidden': [256, 128], 'dropout': 0.2, 'epochs': 30,
                   'batch_size': 512, 'lr': 0.002, 'neg_samples': 8, 'weight_decay': 1e-5}

# Config cho CL4Rec (optimized)
CONFIG_CL4REC = {'dim': 128, 'hidden': [256, 128], 'dropout': 0.15, 'epochs': 50,
                'batch_size': 512, 'lr': 0.003, 'neg_samples': 12, 'weight_decay': 1e-5}

print("Baseline Config:", CONFIG_BASELINE)
print("CL4Rec Config:", CONFIG_CL4REC)

# Cell 6: Matrix Factorization
class MatrixFactorization(nn.Module):
    def __init__(self, n_users, n_items, dim=64):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        self.user_bias = nn.Embedding(n_users, 1)
        self.item_bias = nn.Embedding(n_items, 1)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)
        nn.init.zeros_(self.user_bias.weight)
        nn.init.zeros_(self.item_bias.weight)
        self.n_items = n_items

    def forward(self, users, pos_items, neg_items):
        u_emb, p_emb, n_emb = self.user_emb(users), self.item_emb(pos_items), self.item_emb(neg_items)
        u_bias, p_bias = self.user_bias(users).squeeze(), self.item_bias(pos_items).squeeze()
        n_bias = self.item_bias(neg_items).squeeze(-1)
        pos_score = (u_emb * p_emb).sum(-1) + u_bias + p_bias
        neg_score = ((u_emb.unsqueeze(1) * n_emb).sum(-1) + u_bias.unsqueeze(1) + n_bias).mean(1)
        return -F.logsigmoid(pos_score - neg_score).mean() + 0.01 * (u_emb.norm(2)**2 + p_emb.norm(2)**2) / users.size(0)

    def predict(self, users, domain_idx=0):
        with torch.no_grad():
            u_emb, u_bias = self.user_emb(users), self.user_bias(users)
            return torch.mm(u_emb, self.item_emb.weight.t()) + u_bias + self.item_bias.weight.t()

# Cell 7: KEEP (CIKM 2022)
class KEEP(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim
        self.shared_user_emb = nn.Embedding(n_users, dim)
        self.shared_item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.shared_user_emb.weight)
        nn.init.xavier_uniform_(self.shared_item_emb.weight)
        self.knowledge_extractor = nn.Sequential(nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim))
        self.domain_user_emb = nn.ModuleList([nn.Embedding(n_users, dim) for _ in range(n_domains)])
        self.domain_item_emb = nn.ModuleList([nn.Embedding(n_items, dim) for _ in range(n_domains)])
        for e in self.domain_user_emb: nn.init.xavier_uniform_(e.weight)
        for e in self.domain_item_emb: nn.init.xavier_uniform_(e.weight)
        self.domain_adapters = nn.ModuleList([nn.Sequential(nn.Linear(dim*2, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim)) for _ in range(n_domains)])

    def forward(self, users, pos_items, neg_items, domain_idx):
        shared_u = self.knowledge_extractor(self.shared_user_emb(users))
        shared_p = self.knowledge_extractor(self.shared_item_emb(pos_items))
        u_emb = self.domain_adapters[domain_idx](torch.cat([shared_u, self.domain_user_emb[domain_idx](users)], -1))
        p_emb = self.domain_adapters[domain_idx](torch.cat([shared_p, self.domain_item_emb[domain_idx](pos_items)], -1))
        shared_n = self.knowledge_extractor(self.shared_item_emb(neg_items.view(-1)))
        n_emb = self.domain_adapters[domain_idx](torch.cat([shared_n, self.domain_item_emb[domain_idx](neg_items.view(-1))], -1))
        n_emb = n_emb.view(users.size(0), neg_items.size(1), -1)
        pos_score = (u_emb * p_emb).sum(-1)
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)
        return -F.logsigmoid(pos_score - neg_score).mean() + 0.001 * u_emb.norm(2)**2 / users.size(0)

    def predict(self, users, domain_idx):
        with torch.no_grad():
            shared_u = self.knowledge_extractor(self.shared_user_emb(users))
            u_emb = self.domain_adapters[domain_idx](torch.cat([shared_u, self.domain_user_emb[domain_idx](users)], -1))
            all_items = torch.arange(self.n_items, device=users.device)
            shared_i = self.knowledge_extractor(self.shared_item_emb(all_items))
            i_emb = self.domain_adapters[domain_idx](torch.cat([shared_i, self.domain_item_emb[domain_idx](all_items)], -1))
            return torch.mm(u_emb, i_emb.t())

# Cell 8: DIIT (CIKM 2024)
class DIIT(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)
        self.invariant_encoder = nn.Sequential(nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim))
        self.specific_encoders = nn.ModuleList([nn.Sequential(nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim)) for _ in range(n_domains)])
        self.discriminator = nn.Sequential(nn.Linear(dim, hidden[1]), nn.ReLU(), nn.Linear(hidden[1], n_domains))
        self.fusion = nn.Sequential(nn.Linear(dim*2, hidden[0]), nn.ReLU(), nn.Linear(hidden[0], dim))

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_raw, p_raw = self.user_emb(users), self.item_emb(pos_items)
        u_inv, p_inv = self.invariant_encoder(u_raw), self.invariant_encoder(p_raw)
        u_spec, p_spec = self.specific_encoders[domain_idx](u_raw), self.specific_encoders[domain_idx](p_raw)
        u_emb = self.fusion(torch.cat([u_inv, u_spec], -1))
        p_emb = self.fusion(torch.cat([p_inv, p_spec], -1))
        n_raw = self.item_emb(neg_items.view(-1))
        n_inv, n_spec = self.invariant_encoder(n_raw), self.specific_encoders[domain_idx](n_raw)
        n_emb = self.fusion(torch.cat([n_inv, n_spec], -1)).view(users.size(0), neg_items.size(1), -1)
        bpr = -F.logsigmoid((u_emb * p_emb).sum(-1) - (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)).mean()
        adv = -F.cross_entropy(self.discriminator(u_inv), torch.full((users.size(0),), domain_idx, device=users.device, dtype=torch.long)) * 0.1
        return bpr + adv + 0.001 * u_emb.norm(2)**2 / users.size(0)

    def predict(self, users, domain_idx):
        with torch.no_grad():
            u_raw = self.user_emb(users)
            u_emb = self.fusion(torch.cat([self.invariant_encoder(u_raw), self.specific_encoders[domain_idx](u_raw)], -1))
            all_items = torch.arange(self.n_items, device=users.device)
            i_raw = self.item_emb(all_items)
            i_emb = self.fusion(torch.cat([self.invariant_encoder(i_raw), self.specific_encoders[domain_idx](i_raw)], -1))
            return torch.mm(u_emb, i_emb.t())

# Cell 9: ECAT (SIGIR 2024)
class ECAT(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)
        self.experts = nn.ModuleList([nn.Sequential(nn.Linear(dim, hidden[0]), nn.ReLU(), nn.Dropout(drop), nn.Linear(hidden[0], dim)) for _ in range(n_domains)])
        self.attention = nn.Sequential(nn.Linear(dim, hidden[1]), nn.ReLU(), nn.Linear(hidden[1], n_domains))
        self.register_buffer('fisher', torch.zeros(n_users, dim))
        self.register_buffer('opt_params', torch.zeros(n_users, dim))

    def encode(self, emb, domain_idx):
        expert_out = [exp(emb) for exp in self.experts]
        attn = F.softmax(self.attention(emb), dim=-1)
        stacked = torch.stack(expert_out, dim=-1)
        weighted = (stacked * attn.unsqueeze(1)).sum(-1)
        return weighted + expert_out[domain_idx]

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_emb = self.encode(self.user_emb(users), domain_idx)
        p_emb = self.encode(self.item_emb(pos_items), domain_idx)
        n_emb = self.encode(self.item_emb(neg_items.view(-1)), domain_idx).view(users.size(0), neg_items.size(1), -1)
        bpr = -F.logsigmoid((u_emb * p_emb).sum(-1) - (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)).mean()
        ewc = 0
        if domain_idx > 0:
            ewc = 0.005 * (self.fisher[users] * (self.user_emb(users) - self.opt_params[users])**2).sum() / users.size(0)
        return bpr + ewc + 0.001 * u_emb.norm(2)**2 / users.size(0)

    def update_fisher(self, train_data, domain_idx):
        users = torch.LongTensor(train_data['users']).unique().to(device)
        self.opt_params[users] = self.user_emb(users).detach()
        self.fisher[users] += 1.0

    def predict(self, users, domain_idx):
        with torch.no_grad():
            u_emb = self.encode(self.user_emb(users), domain_idx)
            all_items = torch.arange(self.n_items, device=users.device)
            i_emb = self.encode(self.item_emb(all_items), domain_idx)
            return torch.mm(u_emb, i_emb.t())

# Cell 10: CTNet (WWW 2023)
class CTNet(nn.Module):
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.2):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim
        self.h1_dim, self.h2_dim = hidden[0], hidden[1]
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)
        self.columns = nn.ModuleList([nn.ModuleDict({'l1': nn.Linear(dim, hidden[0]), 'l2': nn.Linear(hidden[0], hidden[1]), 'l3': nn.Linear(hidden[1], dim)}) for _ in range(n_domains)])
        self.laterals = nn.ModuleList([nn.ModuleDict({'lat1': nn.Linear(hidden[0]*d, hidden[0]), 'lat2': nn.Linear(hidden[1]*d, hidden[1])}) for d in range(1, n_domains)])
        self.gates = nn.ModuleList([nn.Sequential(nn.Linear(dim, hidden[1]), nn.Sigmoid()) for _ in range(n_domains)])
        self.drop = nn.Dropout(drop)
        self.h1_cache, self.h2_cache = {}, {}

    def column_forward(self, x, d, store=False):
        col = self.columns[d]
        h1 = self.drop(F.relu(col['l1'](x)))
        if d > 0 and self.h1_cache:
            prev = torch.cat([self.h1_cache.get(i, torch.zeros(x.size(0), self.h1_dim, device=x.device)) for i in range(d)], -1)
            h1 = h1 + self.laterals[d-1]['lat1'](prev)
        h2 = self.drop(F.relu(col['l2'](h1)))
        if d > 0 and self.h2_cache:
            prev = torch.cat([self.h2_cache.get(i, torch.zeros(x.size(0), self.h2_dim, device=x.device)) for i in range(d)], -1)
            h2 = h2 + self.laterals[d-1]['lat2'](prev)
        h3 = col['l3'](h2)
        out = self.gates[d](x) * h3 + (1 - self.gates[d](x)) * x
        if store: self.h1_cache[d], self.h2_cache[d] = h1.detach(), h2.detach()
        return out

    def forward(self, users, pos_items, neg_items, domain_idx):
        u_emb = self.column_forward(self.user_emb(users), domain_idx, store=True)
        p_emb = self.column_forward(self.item_emb(pos_items), domain_idx)
        n_emb = self.column_forward(self.item_emb(neg_items.view(-1)), domain_idx).view(users.size(0), neg_items.size(1), -1)
        return -F.logsigmoid((u_emb * p_emb).sum(-1) - (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)).mean() + 0.001 * u_emb.norm(2)**2 / users.size(0)

    def predict(self, users, domain_idx):
        with torch.no_grad():
            self.h1_cache, self.h2_cache = {}, {}
            u_emb = self.column_forward(self.user_emb(users), domain_idx)
            all_items = torch.arange(self.n_items, device=users.device)
            i_emb = self.column_forward(self.item_emb(all_items), domain_idx)
            return torch.mm(u_emb, i_emb.t())

# Cell 11: CL4Rec (Ours) - OPTIMIZED VERSION
class CL4Rec(nn.Module):
    """CL4Rec with Domain Masking and Domain Specialization - Optimized"""
    def __init__(self, n_users, n_items, n_domains, dim=128, hidden=[256,128], drop=0.15):
        super().__init__()
        self.n_users, self.n_items, self.n_domains, self.dim = n_users, n_items, n_domains, dim

        # Embeddings with better initialization
        self.user_emb = nn.Embedding(n_users, dim)
        self.item_emb = nn.Embedding(n_items, dim)
        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

        # Domain masks with optimized initialization
        self.user_masks = nn.Parameter(torch.randn(n_domains, dim) * 0.1 + 0.6)
        self.item_masks = nn.Parameter(torch.randn(n_domains, dim) * 0.1 + 0.6)

        # MLP with GELU activation and LayerNorm
        self.u_mlp = nn.Sequential(
            nn.Linear(dim, hidden[0]), nn.GELU(), nn.Dropout(drop),
            nn.Linear(hidden[0], hidden[1]), nn.GELU(), nn.Dropout(drop),
            nn.Linear(hidden[1], dim)
        )
        self.i_mlp = nn.Sequential(
            nn.Linear(dim, hidden[0]), nn.GELU(), nn.Dropout(drop),
            nn.Linear(hidden[0], hidden[1]), nn.GELU(), nn.Dropout(drop),
            nn.Linear(hidden[1], dim)
        )
        self.u_norm = nn.LayerNorm(dim)
        self.i_norm = nn.LayerNorm(dim)

    def get_mask(self, d, t='user'):
        masks = self.user_masks if t == 'user' else self.item_masks
        return torch.sigmoid(masks[d])

    def get_combined_mask(self, t='user'):
        """Combine masks using max + mean for inference"""
        masks = self.user_masks if t == 'user' else self.item_masks
        sigmoid_masks = torch.sigmoid(masks)
        return 0.7 * sigmoid_masks.max(dim=0)[0] + 0.3 * sigmoid_masks.mean(dim=0)

    def forward(self, users, pos_items, neg_items, domain_idx):
        # Get embeddings
        ue = self.user_emb(users)
        pe = self.item_emb(pos_items)
        ne = self.item_emb(neg_items.view(-1))

        # Apply domain masking
        um, im = self.get_mask(domain_idx, 'user'), self.get_mask(domain_idx, 'item')
        ue = ue * um
        pe = pe * im
        ne = ne * im

        # Apply MLP with residual + LayerNorm
        u_emb = self.u_norm(ue + self.u_mlp(ue))
        p_emb = self.i_norm(pe + self.i_mlp(pe))
        n_emb = self.i_norm(ne + self.i_mlp(ne)).view(users.size(0), neg_items.size(1), -1)

        # BPR loss with margin
        pos_score = (u_emb * p_emb).sum(-1)
        neg_score = (u_emb.unsqueeze(1) * n_emb).sum(-1).mean(1)
        loss = -F.logsigmoid(pos_score - neg_score + 0.5).mean()

        # Regularization
        reg = 0.0005 * (u_emb.norm(2)**2 + p_emb.norm(2)**2 + n_emb.norm(2)**2) / users.size(0)

        # Mask diversity loss
        if domain_idx > 0:
            mask_div = 0
            for i in range(domain_idx):
                prev_um = self.get_mask(i, 'user')
                prev_im = self.get_mask(i, 'item')
                mask_div += F.cosine_similarity(um.unsqueeze(0), prev_um.unsqueeze(0)).abs().mean()
                mask_div += F.cosine_similarity(im.unsqueeze(0), prev_im.unsqueeze(0)).abs().mean()
            loss += 0.01 * mask_div / domain_idx

        return loss + reg

    def predict(self, users, domain_idx=0):
        with torch.no_grad():
            ue = self.user_emb(users)
            ie = self.item_emb.weight

            # Use combined mask for inference
            um, im = self.get_combined_mask('user'), self.get_combined_mask('item')
            ue = ue * um
            ie = ie * im

            u_emb = self.u_norm(ue + self.u_mlp(ue))
            i_emb = self.i_norm(ie + self.i_mlp(ie))

            return torch.mm(u_emb, i_emb.t())

    def get_grad_mask(self, d):
        if d == 0:
            return None, None
        um = 1 - torch.stack([self.get_mask(i, 'user') for i in range(d)]).max(0)[0]
        im = 1 - torch.stack([self.get_mask(i, 'item') for i in range(d)]).max(0)[0]
        return um.clamp(min=0.1), im.clamp(min=0.1)

# Cell 12: Training Functions
def train_mf(train_data, domains, config):
    models = {}
    for domain in domains:
        print(f"  MF: {domain}")
        torch.manual_seed(SEED)
        model = MatrixFactorization(num_users, num_items, config['dim']).to(device)
        ds = BPRDataset(train_data[domain]['users'], train_data[domain]['items'],
                       train_data[domain]['user_items'], num_items, config['neg_samples'], domain_items[domain])
        loader = DataLoader(ds, config['batch_size'], True, collate_fn=collate_fn, num_workers=0)
        opt = torch.optim.Adam(model.parameters(), config['lr'])
        model.train()
        for _ in range(config['epochs']):
            for u, p, n in loader:
                opt.zero_grad()
                model(u.to(device), p.to(device), n.to(device)).backward()
                opt.step()
        models[domain] = model
    return models

def train_baseline(model, train_data, domains, config):
    """Standard training for baselines"""
    for di, domain in enumerate(domains):
        print(f"  {domain}")
        ds = BPRDataset(train_data[domain]['users'], train_data[domain]['items'],
                       train_data[domain]['user_items'], num_items, config['neg_samples'])
        loader = DataLoader(ds, config['batch_size'], True, collate_fn=collate_fn, num_workers=0)
        opt = torch.optim.AdamW(model.parameters(), config['lr'] * (0.5 if di > 0 else 1), weight_decay=config['weight_decay'])
        model.train()
        for _ in range(config['epochs']):
            for u, p, n in loader:
                opt.zero_grad()
                model(u.to(device), p.to(device), n.to(device), di).backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                opt.step()
        if hasattr(model, 'update_fisher'):
            model.update_fisher(train_data[domain], di)

def train_cl4rec(model, train_data, domains, config):
    """Optimized training for CL4Rec"""
    for di, domain in enumerate(domains):
        print(f"  {domain}")
        ds = BPRDataset(train_data[domain]['users'], train_data[domain]['items'],
                       train_data[domain]['user_items'], num_items, config['neg_samples'],
                       domain_items[domain])  # Domain-specific negative sampling
        loader = DataLoader(ds, config['batch_size'], True, collate_fn=collate_fn, num_workers=0)

        # Differential learning rates
        if di == 0:
            opt = torch.optim.AdamW(model.parameters(), config['lr'], weight_decay=config['weight_decay'])
        else:
            param_groups = [
                {'params': model.user_emb.parameters(), 'lr': config['lr'] * 0.2},
                {'params': model.item_emb.parameters(), 'lr': config['lr'] * 0.2},
                {'params': [model.user_masks, model.item_masks], 'lr': config['lr'] * 4},
                {'params': model.u_mlp.parameters(), 'lr': config['lr'] * 0.8},
                {'params': model.i_mlp.parameters(), 'lr': config['lr'] * 0.8},
                {'params': model.u_norm.parameters(), 'lr': config['lr']},
                {'params': model.i_norm.parameters(), 'lr': config['lr']},
            ]
            opt = torch.optim.AdamW(param_groups, weight_decay=config['weight_decay'])

        sched = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(opt, T_0=config['epochs']//3, T_mult=1, eta_min=config['lr']*0.01)

        model.train()
        for ep in range(config['epochs']):
            for u, p, n in loader:
                u, p, n = u.to(device), p.to(device), n.to(device)
                opt.zero_grad()
                loss = model(u, p, n, di)
                loss.backward()

                # Gradient masking
                um, im = model.get_grad_mask(di)
                if um is not None:
                    if model.user_emb.weight.grad is not None:
                        model.user_emb.weight.grad *= um
                    if model.item_emb.weight.grad is not None:
                        model.item_emb.weight.grad *= im

                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                opt.step()
            sched.step()

# Cell 13: Evaluation
@torch.no_grad()
def evaluate(model, test_data, train_data, domains, k=50, user_filter=None, is_mf=False, mf_models=None):
    all_train_ui = defaultdict(set)
    for d in domains:
        for u, its in train_data[d]['user_items'].items():
            all_train_ui[u].update(its)

    results = {}
    for di, domain in enumerate(domains):
        curr_model = mf_models[domain] if is_mf else model
        curr_model.eval()

        users = list(test_data[domain]['user_test_item'].keys())
        if user_filter: users = [u for u in users if u in user_filter]
        if not users:
            results[domain] = {'R@10': 0, 'R@20': 0, 'R@50': 0}
            continue

        h10, h20, h50, tot = 0, 0, 0, 0
        for i in range(0, len(users), 128):
            batch = users[i:i+128]
            uids = torch.LongTensor(batch).to(device)
            scores = curr_model.predict(uids, di).cpu()

            for j, u in enumerate(batch):
                for it in all_train_ui.get(u, set()):
                    if it < num_items: scores[j, it] = float('-inf')

            topk = torch.topk(scores, min(k, scores.size(1)), 1)[1].numpy()
            for j, u in enumerate(batch):
                ti = test_data[domain]['user_test_item'][u]
                if ti in topk[j]: h50 += 1
                if ti in topk[j, :20]: h20 += 1
                if ti in topk[j, :10]: h10 += 1
                tot += 1

        results[domain] = {'R@10': h10/tot*100, 'R@20': h20/tot*100, 'R@50': h50/tot*100}
    return results

def full_eval(model, test_data, train_data, domains, is_mf=False, mf_models=None):
    return {
        'Active': evaluate(model, test_data, train_data, domains, user_filter=active_users, is_mf=is_mf, mf_models=mf_models),
        'ColdStart': evaluate(model, test_data, train_data, domains, user_filter=coldstart_users, is_mf=is_mf, mf_models=mf_models),
        'Overall': evaluate(model, test_data, train_data, domains, user_filter=None, is_mf=is_mf, mf_models=mf_models)
    }

# Cell 14: Run All Experiments
print("="*60)
print("TRAINING ALL MODELS")
print("="*60)

all_results, times = {}, {}

# 1. MF
print("\n1. Matrix Factorization")
t0 = time.time()
mf_models = train_mf(train_data, DOMAINS, CONFIG_BASELINE)
times['MF'] = time.time() - t0
all_results['MF'] = full_eval(None, test_data, train_data, DOMAINS, is_mf=True, mf_models=mf_models)
print(f"  Done: {times['MF']:.0f}s")

# 2. KEEP
print("\n2. KEEP")
torch.manual_seed(SEED); torch.cuda.manual_seed(SEED)
keep = KEEP(num_users, num_items, len(DOMAINS), CONFIG_BASELINE['dim'], CONFIG_BASELINE['hidden'], CONFIG_BASELINE['dropout']).to(device)
t0 = time.time()
train_baseline(keep, train_data, DOMAINS, CONFIG_BASELINE)
times['KEEP'] = time.time() - t0
all_results['KEEP'] = full_eval(keep, test_data, train_data, DOMAINS)
print(f"  Done: {times['KEEP']:.0f}s")

# 3. DIIT
print("\n3. DIIT")
torch.manual_seed(SEED); torch.cuda.manual_seed(SEED)
diit = DIIT(num_users, num_items, len(DOMAINS), CONFIG_BASELINE['dim'], CONFIG_BASELINE['hidden'], CONFIG_BASELINE['dropout']).to(device)
t0 = time.time()
train_baseline(diit, train_data, DOMAINS, CONFIG_BASELINE)
times['DIIT'] = time.time() - t0
all_results['DIIT'] = full_eval(diit, test_data, train_data, DOMAINS)
print(f"  Done: {times['DIIT']:.0f}s")

# 4. ECAT
print("\n4. ECAT")
torch.manual_seed(SEED); torch.cuda.manual_seed(SEED)
ecat = ECAT(num_users, num_items, len(DOMAINS), CONFIG_BASELINE['dim'], CONFIG_BASELINE['hidden'], CONFIG_BASELINE['dropout']).to(device)
t0 = time.time()
train_baseline(ecat, train_data, DOMAINS, CONFIG_BASELINE)
times['ECAT'] = time.time() - t0
all_results['ECAT'] = full_eval(ecat, test_data, train_data, DOMAINS)
print(f"  Done: {times['ECAT']:.0f}s")

# 5. CTNet
print("\n5. CTNet")
torch.manual_seed(SEED); torch.cuda.manual_seed(SEED)
ctnet = CTNet(num_users, num_items, len(DOMAINS), CONFIG_BASELINE['dim'], CONFIG_BASELINE['hidden'], CONFIG_BASELINE['dropout']).to(device)
t0 = time.time()
train_baseline(ctnet, train_data, DOMAINS, CONFIG_BASELINE)
times['CTNet'] = time.time() - t0
all_results['CTNet'] = full_eval(ctnet, test_data, train_data, DOMAINS)
print(f"  Done: {times['CTNet']:.0f}s")

# 6. CL4Rec (OPTIMIZED)
print("\n6. CL4Rec (Ours) ⭐")
torch.manual_seed(SEED); torch.cuda.manual_seed(SEED)
cl4rec = CL4Rec(num_users, num_items, len(DOMAINS), CONFIG_CL4REC['dim'], CONFIG_CL4REC['hidden'], CONFIG_CL4REC['dropout']).to(device)
t0 = time.time()
train_cl4rec(cl4rec, train_data, DOMAINS, CONFIG_CL4REC)
times['CL4Rec'] = time.time() - t0
all_results['CL4Rec'] = full_eval(cl4rec, test_data, train_data, DOMAINS)
print(f"  Done: {times['CL4Rec']:.0f}s")

# Cell 15: Results
methods = ['MF', 'KEEP', 'DIIT', 'ECAT', 'CTNet', 'CL4Rec']

print("\n" + "="*90)
print("OVERALL R@50")
print("="*90)
print(f"{'Method':<10} " + " ".join([f'{d:>12}' for d in DOMAINS]) + f" {'Mean':>10} {'Time':>8}")
print("-"*90)
for m in methods:
    vals = [all_results[m]['Overall'][d]['R@50'] for d in DOMAINS]
    marker = " ⭐" if m == 'CL4Rec' else ""
    print(f"{m:<10} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {np.mean(vals):>9.2f}%{marker} {times[m]:>6.0f}s")

print("\n" + "="*80)
print("ACTIVE USERS R@50")
print("="*80)
for m in methods:
    vals = [all_results[m]['Active'][d]['R@50'] for d in DOMAINS]
    marker = " ⭐" if m == 'CL4Rec' else ""
    print(f"{m:<10} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {np.mean(vals):>9.2f}%{marker}")

print("\n" + "="*80)
print("COLD-START R@50")
print("="*80)
for m in methods:
    vals = [all_results[m]['ColdStart'][d]['R@50'] for d in DOMAINS]
    marker = " ⭐" if m == 'CL4Rec' else ""
    print(f"{m:<10} " + " ".join([f'{v:>11.2f}%' for v in vals]) + f" {np.mean(vals):>9.2f}%{marker}")

# Cell 16: Improvement Analysis
print("\n" + "="*60)
print("CL4REC vs BASELINES")
print("="*60)
cl4rec_mean = np.mean([all_results['CL4Rec']['Overall'][d]['R@50'] for d in DOMAINS])
print(f"\n{'Method':<10} {'Mean R@50':>12} {'Δ':>12} {'Relative':>12}")
print("-"*50)
for m in methods:
    val = np.mean([all_results[m]['Overall'][d]['R@50'] for d in DOMAINS])
    delta = cl4rec_mean - val
    rel = delta / val * 100 if val > 0 else 0
    if m == 'CL4Rec':
        print(f"{m:<10} {val:>11.2f}% {'(ours) ⭐':>12} {'-':>12}")
    else:
        print(f"{m:<10} {val:>11.2f}% {delta:>+11.2f}% {rel:>+11.1f}%")

# Cell 17: Visualization
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
colors = {'MF':'#95a5a6', 'KEEP':'#3498db', 'DIIT':'#9b59b6', 'ECAT':'#e67e22', 'CTNet':'#1abc9c', 'CL4Rec':'#e74c3c'}

# 1. By Domain
ax = axes[0,0]
x = np.arange(len(DOMAINS))
w = 0.12
for i, m in enumerate(methods):
    ax.bar(x + i*w, [all_results[m]['Overall'][d]['R@50'] for d in DOMAINS], w, label=m, color=colors[m])
ax.set_xticks(x + w*2.5); ax.set_xticklabels(DOMAINS)
ax.set_ylabel('R@50 (%)'); ax.set_title('Overall R@50 by Domain'); ax.legend(fontsize=7)

# 2. Mean
ax = axes[0,1]
vals = [np.mean([all_results[m]['Overall'][d]['R@50'] for d in DOMAINS]) for m in methods]
bars = ax.bar(methods, vals, color=[colors[m] for m in methods])
ax.set_ylabel('Mean R@50 (%)'); ax.set_title('Mean Performance')
for b,v in zip(bars,vals): ax.text(b.get_x()+b.get_width()/2, v+0.2, f'{v:.1f}', ha='center', fontsize=8)

# 3. Active vs Cold
ax = axes[0,2]
x = np.arange(len(methods))
act = [np.mean([all_results[m]['Active'][d]['R@50'] for d in DOMAINS]) for m in methods]
cold = [np.mean([all_results[m]['ColdStart'][d]['R@50'] for d in DOMAINS]) for m in methods]
ax.bar(x-0.2, act, 0.35, label='Active', color='#2ecc71')
ax.bar(x+0.2, cold, 0.35, label='Cold-Start', color='#e74c3c')
ax.set_xticks(x); ax.set_xticklabels(methods, fontsize=8)
ax.set_ylabel('Mean R@50 (%)'); ax.set_title('Active vs Cold-Start'); ax.legend()

# 4. Heatmap
ax = axes[1,0]
data = [[all_results[m]['Overall'][d]['R@50'] for d in DOMAINS] for m in methods]
sns.heatmap(data, annot=True, fmt='.1f', cmap='YlOrRd', xticklabels=DOMAINS, yticklabels=methods, ax=ax)
ax.set_title('R@50 Heatmap')

# 5. Improvement over MF
ax = axes[1,1]
mf_vals = {d: all_results['MF']['Overall'][d]['R@50'] for d in DOMAINS}
for m in methods[1:]:
    imp = [all_results[m]['Overall'][d]['R@50'] - mf_vals[d] for d in DOMAINS]
    ax.plot(DOMAINS, imp, 'o-', label=m, color=colors[m], lw=2, ms=6)
ax.axhline(0, color='k', ls='--', alpha=0.5)
ax.set_ylabel('Improvement (%)'); ax.set_title('Improvement over MF'); ax.legend(fontsize=7)

# 6. Time
ax = axes[1,2]
ax.bar(methods, [times[m] for m in methods], color=[colors[m] for m in methods])
ax.set_ylabel('Time (s)'); ax.set_title('Training Time')

plt.tight_layout()
plt.savefig('results.png', dpi=150)
plt.show()

# Cell 18: Save CSV
rows = []
for m in methods:
    for ut in ['Active', 'ColdStart', 'Overall']:
        for d in DOMAINS:
            rows.append({'Method': m, 'UserType': ut, 'Domain': d,
                        'R@10': all_results[m][ut][d]['R@10'],
                        'R@20': all_results[m][ut][d]['R@20'],
                        'R@50': all_results[m][ut][d]['R@50'],
                        'Time': times[m]})
df = pd.DataFrame(rows)
df.to_csv('results.csv', index=False)
print("Saved to results.csv")
print("\nSummary:")
print(df.groupby(['Method','UserType'])[['R@10','R@20','R@50']].mean().round(2))